BaseOutputDocInterface
ParamListTypes
SectionTypes
virtual BaseOutputDocInterface::~BaseOutputDocInterface()
virtual bool BaseOutputDocInterface::parseText(const QCString &s)
virtual void BaseOutputDocInterface::startItemList()=0
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Referenced by OutputList::startItemList.
virtual void BaseOutputDocInterface::startItemListItem()=0
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Referenced by OutputList::startItemListItem.
virtual void BaseOutputDocInterface::endItemListItem()=0
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Referenced by OutputList::endItemListItem.
virtual void BaseOutputDocInterface::endItemList()=0
Ends a bullet list: e.g. </ul> in html
Referenced by OutputList::endItemList.
virtual void BaseOutputDocInterface::docify(const char *s)=0
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Referenced by OutputList::docify.
virtual void BaseOutputDocInterface::writeChar(char c)=0
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Referenced by OutputList::writeChar.
virtual void BaseOutputDocInterface::writeString(const char *text)=0
Writes an ASCII string to the output, without converting special characters.
Referenced by OutputList::writeString.
virtual void BaseOutputDocInterface::startParagraph()=0
Starts a new paragraphStarts a new paragraph
Referenced by OutputList::startParagraph.
virtual void BaseOutputDocInterface::endParagraph()=0
Ends a paragraph
Referenced by OutputList::endParagraph.
virtual void BaseOutputDocInterface::writeObjectLink(const char *ref, const char *file, const char *anchor, const char *name)=0
Writes a link to an object in the documentation. ref If this is non-zero, the object is to be found in an external documentation file. file The file in which the object is located. anchor The anchor uniquely identifying the object within the file. name The text to display as a placeholder for the link.
Referenced by OutputList::writeObjectLink.
virtual void BaseOutputDocInterface::startHtmlLink(const char *url)=0
Starts a (link to an) URL found in the documentation. url The URL to link to.
Referenced by OutputList::startHtmlLink.
virtual void BaseOutputDocInterface::endHtmlLink()=0
Ends a link started by startHtmlLink().
Referenced by OutputList::endHtmlLink.
virtual void BaseOutputDocInterface::startBold()=0
Changes the text font to bold face. The bold section ends with endBold()
Referenced by OutputList::startBold.
virtual void BaseOutputDocInterface::endBold()=0
End a section of text displayed in bold face.
Referenced by OutputList::endBold.
virtual void BaseOutputDocInterface::startTypewriter()=0
Changes the text font to fixed size. The section ends with endTypewriter()
Referenced by OutputList::startTypewriter.
virtual void BaseOutputDocInterface::endTypewriter()=0
End a section of text displayed in typewriter style.
Referenced by OutputList::endTypewriter.
virtual void BaseOutputDocInterface::startEmphasis()=0
Changes the text font to italic. The italic section ends with endEmphasis()
Referenced by OutputList::startEmphasis.
virtual void BaseOutputDocInterface::endEmphasis()=0
Ends a section of text displayed in italic.
Referenced by OutputList::endEmphasis.
virtual void BaseOutputDocInterface::startCodeFragment()=0
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Referenced by OutputList::startCodeFragment.
virtual void BaseOutputDocInterface::endCodeFragment()=0
Ends a source code fragment
Referenced by OutputList::endCodeFragment.
virtual void BaseOutputDocInterface::writeRuler()=0
Writes a horizontal ruler to the output
Referenced by OutputList::writeRuler.
virtual void BaseOutputDocInterface::startDescription()=0
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Referenced by OutputList::startDescription.
virtual void BaseOutputDocInterface::endDescription()=0
Ends a description list: e.g. </dl> in HTML
Referenced by OutputList::endDescription.
virtual void BaseOutputDocInterface::startDescItem()=0
Starts an item of a description list: e.g. <dt> in HTML.
Referenced by OutputList::startDescItem.
virtual void BaseOutputDocInterface::startDescForItem()=0
virtual void BaseOutputDocInterface::endDescForItem()=0
virtual void BaseOutputDocInterface::endDescItem()=0
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Referenced by OutputList::endDescItem.
virtual void BaseOutputDocInterface::startCenter()=0
virtual void BaseOutputDocInterface::endCenter()=0
virtual void BaseOutputDocInterface::startSmall()=0
virtual void BaseOutputDocInterface::endSmall()=0
virtual void BaseOutputDocInterface::startSimpleSect(SectionTypes t, const char *file, const char *anchor, const char *title)=0
virtual void BaseOutputDocInterface::endSimpleSect()=0
virtual void BaseOutputDocInterface::startParamList(ParamListTypes t, const char *title)=0
virtual void BaseOutputDocInterface::endParamList()=0
virtual void BaseOutputDocInterface::startTitle()=0
virtual void BaseOutputDocInterface::endTitle()=0
virtual void BaseOutputDocInterface::writeAnchor(const char *fileName, const char *name)=0
virtual void BaseOutputDocInterface::startSection(const char *, const char *, SectionInfo::SectionType)=0
virtual void BaseOutputDocInterface::endSection(const char *, SectionInfo::SectionType)=0
virtual void BaseOutputDocInterface::lineBreak(const char *style)=0
virtual void BaseOutputDocInterface::addIndexItem(const char *s1, const char *s2)=0
virtual void BaseOutputDocInterface::writeNonBreakableSpace(int)=0
virtual void BaseOutputDocInterface::startDescTable(const char *title)=0
virtual void BaseOutputDocInterface::endDescTable()=0
virtual void BaseOutputDocInterface::startDescTableTitle()=0
virtual void BaseOutputDocInterface::endDescTableTitle()=0
virtual void BaseOutputDocInterface::startDescTableData()=0
virtual void BaseOutputDocInterface::endDescTableData()=0
virtual void BaseOutputDocInterface::startTextLink(const char *file, const char *anchor)=0
virtual void BaseOutputDocInterface::endTextLink()=0
virtual void BaseOutputDocInterface::startPageRef()=0
virtual void BaseOutputDocInterface::endPageRef(const char *, const char *)=0
virtual void BaseOutputDocInterface::startSubsection()=0
virtual void BaseOutputDocInterface::endSubsection()=0
virtual void BaseOutputDocInterface::startSubsubsection()=0
virtual void BaseOutputDocInterface::endSubsubsection()=0