GroupDef
bool GroupDef::visited
QCString GroupDef::title
bool GroupDef::titleSet
QCString GroupDef::fileName
FileList* GroupDef::fileList
ClassSDict* GroupDef::classSDict
NamespaceSDict* GroupDef::namespaceSDict
GroupList* GroupDef::groupList
PageSDict* GroupDef::pageDict
PageSDict* GroupDef::exampleDict
DirList* GroupDef::dirList
MemberList* GroupDef::allMemberList
MemberNameInfoSDict* GroupDef::allMemberNameInfoSDict
Definition* GroupDef::groupScope
QList<MemberList> GroupDef::m_memberLists
MemberGroupSDict* GroupDef::memberGroupSDict
GroupDef::GroupDef(const char *fileName, int line, const char *name, const char *title, const char *refFileName=0)
GroupDef::~GroupDef()
DefType GroupDef::definitionType() const
Use this for dynamic inspection of the type of the derived class
QCString GroupDef::getOutputFileBase() const
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
References Definition::isReference.
Referenced by PageDef::getOutputFileBase.
QCString GroupDef::anchor() const
Returns the anchor within a page where this item can be found
QCString GroupDef::displayName(bool=TRUE) const
Returns the name of the definition as it appears in the output
References Definition::name.
const char* GroupDef::groupTitle() const
void GroupDef::setGroupTitle(const char *newtitle)
bool GroupDef::hasGroupTitle() const
void GroupDef::addFile(const FileDef *def)
bool GroupDef::addClass(const ClassDef *def)
bool GroupDef::addNamespace(const NamespaceDef *def)
void GroupDef::addGroup(const GroupDef *def)
void GroupDef::addParentGroup(const GroupDef *def)
void GroupDef::addPage(PageDef *def)
void GroupDef::addExample(const PageDef *def)
void GroupDef::addDir(const DirDef *dd)
bool GroupDef::insertMember(MemberDef *def, bool docOnly=FALSE)
void GroupDef::removeMember(MemberDef *md)
bool GroupDef::containsGroup(const GroupDef *def)
void GroupDef::writeDocumentation(OutputList &ol)
void GroupDef::writeMemberPages(OutputList &ol)
void GroupDef::writeQuickMemberLinks(OutputList &ol, MemberDef *currentMd) const
int GroupDef::countMembers() const
bool GroupDef::isLinkableInProject() const
Returns TRUE iff it is possible to link to this item within this project.
References isLinkable, Definition::isReference.
bool GroupDef::isLinkable() const
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
References Definition::hasUserDocumentation.
Referenced by getDefs, isLinkableInProject.
bool GroupDef::isASubGroup() const
void GroupDef::computeAnchors()
Compute the HTML anchor names for all members in the group
void GroupDef::addMembersToMemberGroup()
void GroupDef::distributeMemberGroupDocumentation()
void GroupDef::findSectionsInDocumentation()
void GroupDef::addListReferences()
void GroupDef::sortMemberLists()
void GroupDef::setGroupScope(Definition *d)
Definition* GroupDef::getGroupScope() const
MemberList * GroupDef::getMemberList(MemberListType lt) const
const QList<MemberList>& GroupDef::getMemberLists() const
MemberGroupSDict* GroupDef::getMemberGroupSDict() const
FileList* GroupDef::getFiles() const
ClassSDict* GroupDef::getClasses() const
NamespaceSDict* GroupDef::getNamespaces() const
GroupList* GroupDef::getSubGroups() const
PageSDict* GroupDef::getPages() const
DirList* GroupDef::getDirs() const
PageSDict* GroupDef::getExamples() const
void GroupDef::sortSubGroups()
void GroupDef::addMemberListToGroup(MemberList *, bool(MemberDef::*)() const)
MemberList * GroupDef::createMemberList(MemberListType lt)
void GroupDef::addMemberToList(MemberListType lt, MemberDef *md)
void GroupDef::writeMemberDeclarations(OutputList &ol, MemberListType lt, const QCString &title)
void GroupDef::writeMemberDocumentation(OutputList &ol, MemberListType lt, const QCString &title)
void GroupDef::removeMemberFromList(MemberListType lt, MemberDef *md)
void GroupDef::writeGroupGraph(OutputList &ol)
void GroupDef::writeFiles(OutputList &ol, const QCString &title)
void GroupDef::writeNamespaces(OutputList &ol, const QCString &title)
void GroupDef::writeNestedGroups(OutputList &ol, const QCString &title)
void GroupDef::writeDirs(OutputList &ol, const QCString &title)
void GroupDef::writeClasses(OutputList &ol, const QCString &title)
void GroupDef::writeInlineClasses(OutputList &ol)
void GroupDef::writePageDocumentation(OutputList &ol)
void GroupDef::writeDetailedDescription(OutputList &ol, const QCString &title)
void GroupDef::writeBriefDescription(OutputList &ol)
void GroupDef::writeMemberGroups(OutputList &ol)
void GroupDef::startMemberDeclarations(OutputList &ol)
void GroupDef::endMemberDeclarations(OutputList &ol)
void GroupDef::startMemberDocumentation(OutputList &ol)
void GroupDef::endMemberDocumentation(OutputList &ol)
void GroupDef::writeAuthorSection(OutputList &ol)
void GroupDef::writeSummaryLinks(OutputList &ol)
void GroupDef::updateLanguage(const Definition *)