ParserManager
QDict<ParserInterface> ParserManager::m_parsers
QDict<ParserInterface> ParserManager::m_extensions
ParserInterface* ParserManager::m_defaultParser
ParserManager::ParserManager()
Creates the parser manager object.
void ParserManager::registerParser(const char *name, ParserInterface *parser, bool defParser=FALSE)
Registers an additional parser.
name A symbolic name of the parser, i.e. "c", "python", "fortran", "vhdl", ... parser The parser that is to be used for the given name. defParser Use this parser as the default parser, used for unregistered file extensions.
bool ParserManager::registerExtension(const char *extension, const char *parserName)
Registers a file extension with a parser with name parserName.
Returns TRUE if the extension was successfully registered.
ParserInterface* ParserManager::getParser(const char *extension)
Gets the interface to the parser associated with given extension.
If there is no parser explicitly registered for the supplied extension, the interface to the default parser will be returned.
Referenced by MarkdownFileParser::parseCode, MarkdownFileParser::parsePrototype, MarkdownFileParser::resetCodeParserState, MemberDef::writeDocumentation, Definition::writeInlineCode, FileDef::writeSource.