TranslatorEnglish
virtual QCString TranslatorEnglish::idLanguage()
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
virtual QCString TranslatorEnglish::latexLanguageSupportCommand()
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example "\\usepackage[german]{babel}\n" or "\\usepackage{polski}\n" "\\usepackage[latin2]{inputenc}\n" "\\usepackage[T1]{fontenc}\n" The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
virtual QCString TranslatorEnglish::idLanguageCharset()
return the language charset. This will be used when transcoding the translatable strings in this file to UTF-8
virtual QCString TranslatorEnglish::trRelatedFunctions()
used in the compound documentation before a list of related functions.
virtual QCString TranslatorEnglish::trRelatedSubscript()
subscript for the related functions.
virtual QCString TranslatorEnglish::trDetailedDescription()
header that is put before the detailed description of files, classes and namespaces.
virtual QCString TranslatorEnglish::trMemberTypedefDocumentation()
header that is put before the list of typedefs.
virtual QCString TranslatorEnglish::trMemberEnumerationDocumentation()
header that is put before the list of enumerations.
virtual QCString TranslatorEnglish::trMemberFunctionDocumentation()
header that is put before the list of member functions.
virtual QCString TranslatorEnglish::trMemberDataDocumentation()
header that is put before the list of member attributes.
virtual QCString TranslatorEnglish::trMore()
this is the text of a link put after brief descriptions.
virtual QCString TranslatorEnglish::trListOfAllMembers()
put in the class documentation
virtual QCString TranslatorEnglish::trMemberList()
used as the title of the "list of all members" page of a class
virtual QCString TranslatorEnglish::trThisIsTheListOfAllMembers()
this is the first part of a sentence that is followed by a class name
virtual QCString TranslatorEnglish::trIncludingInheritedMembers()
this is the remainder of the sentence after the class name
virtual QCString TranslatorEnglish::trGeneratedAutomatically(const char *s)
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
virtual QCString TranslatorEnglish::trEnumName()
put after an enum name in the list of all members
virtual QCString TranslatorEnglish::trEnumValue()
put after an enum value in the list of all members
virtual QCString TranslatorEnglish::trDefinedIn()
put after an undocumented member in the list of all members
virtual QCString TranslatorEnglish::trModules()
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
virtual QCString TranslatorEnglish::trClassHierarchy()
This is put above each page as a link to the class hierarchy
virtual QCString TranslatorEnglish::trCompoundList()
This is put above each page as a link to the list of annotated classes
virtual QCString TranslatorEnglish::trFileList()
This is put above each page as a link to the list of documented files
virtual QCString TranslatorEnglish::trCompoundMembers()
This is put above each page as a link to all members of compounds.
virtual QCString TranslatorEnglish::trFileMembers()
This is put above each page as a link to all members of files.
virtual QCString TranslatorEnglish::trRelatedPages()
This is put above each page as a link to all related pages.
virtual QCString TranslatorEnglish::trExamples()
This is put above each page as a link to all examples.
virtual QCString TranslatorEnglish::trSearch()
This is put above each page as a link to the search engine.
virtual QCString TranslatorEnglish::trClassHierarchyDescription()
This is an introduction to the class hierarchy.
virtual QCString TranslatorEnglish::trFileListDescription(bool extractAll)
This is an introduction to the list with all files.
virtual QCString TranslatorEnglish::trCompoundListDescription()
This is an introduction to the annotated compound list.
virtual QCString TranslatorEnglish::trCompoundMembersDescription(bool extractAll)
This is an introduction to the page with all class members.
virtual QCString TranslatorEnglish::trFileMembersDescription(bool extractAll)
This is an introduction to the page with all file members.
virtual QCString TranslatorEnglish::trExamplesDescription()
This is an introduction to the page with the list of all examples
virtual QCString TranslatorEnglish::trRelatedPagesDescription()
This is an introduction to the page with the list of related pages
virtual QCString TranslatorEnglish::trModulesDescription()
This is an introduction to the page with the list of class/file groups
virtual QCString TranslatorEnglish::trDocumentation()
This is used in HTML as the title of index.html.
virtual QCString TranslatorEnglish::trModuleIndex()
This is used in LaTeX as the title of the chapter with the index of all groups.
virtual QCString TranslatorEnglish::trHierarchicalIndex()
This is used in LaTeX as the title of the chapter with the class hierarchy.
virtual QCString TranslatorEnglish::trCompoundIndex()
This is used in LaTeX as the title of the chapter with the annotated compound index.
virtual QCString TranslatorEnglish::trFileIndex()
This is used in LaTeX as the title of the chapter with the list of all files.
virtual QCString TranslatorEnglish::trModuleDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
virtual QCString TranslatorEnglish::trClassDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
virtual QCString TranslatorEnglish::trFileDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all files.
virtual QCString TranslatorEnglish::trExampleDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
virtual QCString TranslatorEnglish::trPageDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all related pages.
virtual QCString TranslatorEnglish::trReferenceManual()
This is used in LaTeX as the title of the document
virtual QCString TranslatorEnglish::trDefines()
This is used in the documentation of a file as a header before the list of defines
virtual QCString TranslatorEnglish::trFuncProtos()
This is used in the documentation of a file as a header before the list of function prototypes
virtual QCString TranslatorEnglish::trTypedefs()
This is used in the documentation of a file as a header before the list of typedefs
virtual QCString TranslatorEnglish::trEnumerations()
This is used in the documentation of a file as a header before the list of enumerations
virtual QCString TranslatorEnglish::trFunctions()
This is used in the documentation of a file as a header before the list of (global) functions
virtual QCString TranslatorEnglish::trVariables()
This is used in the documentation of a file as a header before the list of (global) variables
virtual QCString TranslatorEnglish::trEnumerationValues()
This is used in the documentation of a file as a header before the list of (global) variables
virtual QCString TranslatorEnglish::trDefineDocumentation()
This is used in the documentation of a file before the list of documentation blocks for defines
virtual QCString TranslatorEnglish::trFunctionPrototypeDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for function prototypes
virtual QCString TranslatorEnglish::trTypedefDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
virtual QCString TranslatorEnglish::trEnumerationTypeDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
virtual QCString TranslatorEnglish::trFunctionDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
virtual QCString TranslatorEnglish::trVariableDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
virtual QCString TranslatorEnglish::trCompounds()
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
virtual QCString TranslatorEnglish::trGeneratedAt(const char *date, const char *projName)
This is used in the standard footer of each page and indicates when the page was generated
virtual QCString TranslatorEnglish::trWrittenBy()
This is part of the sentence used in the standard footer of each page.
virtual QCString TranslatorEnglish::trClassDiagram(const char *clName)
this text is put before a class diagram
virtual QCString TranslatorEnglish::trForInternalUseOnly()
this text is generated when the \internal command is used.
virtual QCString TranslatorEnglish::trWarning()
this text is generated when the \warning command is used.
virtual QCString TranslatorEnglish::trVersion()
this text is generated when the \version command is used.
virtual QCString TranslatorEnglish::trDate()
this text is generated when the \date command is used.
virtual QCString TranslatorEnglish::trReturns()
this text is generated when the \return command is used.
virtual QCString TranslatorEnglish::trSeeAlso()
this text is generated when the \sa command is used.
virtual QCString TranslatorEnglish::trParameters()
this text is generated when the \param command is used.
virtual QCString TranslatorEnglish::trExceptions()
this text is generated when the \exception command is used.
virtual QCString TranslatorEnglish::trGeneratedBy()
this text is used in the title page of a LaTeX document.
virtual QCString TranslatorEnglish::trNamespaceList()
used as the title of page containing all the index of all namespaces.
virtual QCString TranslatorEnglish::trNamespaceListDescription(bool extractAll)
used as an introduction to the namespace list
virtual QCString TranslatorEnglish::trFriends()
used in the class documentation as a header before the list of all friends of a class
virtual QCString TranslatorEnglish::trRelatedFunctionDocumentation()
used in the class documentation as a header before the list of all related classes
virtual QCString TranslatorEnglish::trCompoundReference(const char *clName, ClassDef::CompoundType compType, bool isTemplate)
used as the title of the HTML page of a class/struct/union
virtual QCString TranslatorEnglish::trFileReference(const char *fileName)
used as the title of the HTML page of a file
virtual QCString TranslatorEnglish::trNamespaceReference(const char *namespaceName)
used as the title of the HTML page of a namespace
virtual QCString TranslatorEnglish::trPublicMembers()
virtual QCString TranslatorEnglish::trPublicSlots()
virtual QCString TranslatorEnglish::trSignals()
virtual QCString TranslatorEnglish::trStaticPublicMembers()
virtual QCString TranslatorEnglish::trProtectedMembers()
virtual QCString TranslatorEnglish::trProtectedSlots()
virtual QCString TranslatorEnglish::trStaticProtectedMembers()
virtual QCString TranslatorEnglish::trPrivateMembers()
virtual QCString TranslatorEnglish::trPrivateSlots()
virtual QCString TranslatorEnglish::trStaticPrivateMembers()
virtual QCString TranslatorEnglish::trWriteList(int numEntries)
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Referenced by trImplementedFromList, trImplementedInList, trInheritedByList, trInheritsList, trReimplementedFromList, trReimplementedInList.
virtual QCString TranslatorEnglish::trInheritsList(int numEntries)
used in class documentation to produce a list of base classes, if class diagrams are disabled.
References trWriteList.
virtual QCString TranslatorEnglish::trInheritedByList(int numEntries)
used in class documentation to produce a list of super classes, if class diagrams are disabled.
References trWriteList.
virtual QCString TranslatorEnglish::trReimplementedFromList(int numEntries)
used in member documentation blocks to produce a list of members that are hidden by this one.
References trWriteList.
virtual QCString TranslatorEnglish::trReimplementedInList(int numEntries)
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
References trWriteList.
virtual QCString TranslatorEnglish::trNamespaceMembers()
This is put above each page as a link to all members of namespaces.
virtual QCString TranslatorEnglish::trNamespaceMemberDescription(bool extractAll)
This is an introduction to the page with all namespace members
virtual QCString TranslatorEnglish::trNamespaceIndex()
This is used in LaTeX as the title of the chapter with the index of all namespaces.
virtual QCString TranslatorEnglish::trNamespaceDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
virtual QCString TranslatorEnglish::trNamespaces()
This is used in the documentation before the list of all namespaces in a file.
virtual QCString TranslatorEnglish::trGeneratedFromFiles(ClassDef::CompoundType compType, bool single)
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
virtual QCString TranslatorEnglish::trAlphabeticalList()
This is in the (quick) index as a link to the alphabetical compound list.
virtual QCString TranslatorEnglish::trReturnValues()
This is used as the heading text for the retval command.
virtual QCString TranslatorEnglish::trMainPage()
This is in the (quick) index as a link to the main page (index.html)
virtual QCString TranslatorEnglish::trPageAbbreviation()
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
virtual QCString TranslatorEnglish::trDefinedAtLineInSourceFile()
virtual QCString TranslatorEnglish::trDefinedInSourceFile()
virtual QCString TranslatorEnglish::trDeprecated()
virtual QCString TranslatorEnglish::trCollaborationDiagram(const char *clName)
this text is put before a collaboration diagram
virtual QCString TranslatorEnglish::trInclDepGraph(const char *fName)
this text is put before an include dependency graph
virtual QCString TranslatorEnglish::trConstructorDocumentation()
header that is put before the list of constructor/destructors.
virtual QCString TranslatorEnglish::trGotoSourceCode()
Used in the file documentation to point to the corresponding sources.
virtual QCString TranslatorEnglish::trGotoDocumentation()
Used in the file sources to point to the corresponding documentation.
virtual QCString TranslatorEnglish::trPrecondition()
Text for the \pre command
virtual QCString TranslatorEnglish::trPostcondition()
Text for the \post command
virtual QCString TranslatorEnglish::trInvariant()
Text for the \invariant command
virtual QCString TranslatorEnglish::trInitialValue()
Text shown before a multi-line variable/enum initialization
virtual QCString TranslatorEnglish::trCode()
Text used the source code in the file index
virtual QCString TranslatorEnglish::trGraphicalHierarchy()
virtual QCString TranslatorEnglish::trGotoGraphicalHierarchy()
virtual QCString TranslatorEnglish::trGotoTextualHierarchy()
virtual QCString TranslatorEnglish::trPageIndex()
virtual QCString TranslatorEnglish::trNote()
virtual QCString TranslatorEnglish::trPublicTypes()
virtual QCString TranslatorEnglish::trPublicAttribs()
virtual QCString TranslatorEnglish::trStaticPublicAttribs()
virtual QCString TranslatorEnglish::trProtectedTypes()
virtual QCString TranslatorEnglish::trProtectedAttribs()
virtual QCString TranslatorEnglish::trStaticProtectedAttribs()
virtual QCString TranslatorEnglish::trPrivateTypes()
virtual QCString TranslatorEnglish::trPrivateAttribs()
virtual QCString TranslatorEnglish::trStaticPrivateAttribs()
virtual QCString TranslatorEnglish::trTodo()
Used as a marker that is put before a \todo item
virtual QCString TranslatorEnglish::trTodoList()
Used as the header of the todo list
virtual QCString TranslatorEnglish::trReferencedBy()
virtual QCString TranslatorEnglish::trRemarks()
virtual QCString TranslatorEnglish::trAttention()
virtual QCString TranslatorEnglish::trInclByDepGraph()
virtual QCString TranslatorEnglish::trSince()
virtual QCString TranslatorEnglish::trLegendTitle()
title of the graph legend page
virtual QCString TranslatorEnglish::trLegendDocs()
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
virtual QCString TranslatorEnglish::trLegend()
text for the link to the legend page
virtual QCString TranslatorEnglish::trTest()
Used as a marker that is put before a test item
virtual QCString TranslatorEnglish::trTestList()
Used as the header of the test list
virtual QCString TranslatorEnglish::trDCOPMethods()
Used as a section header for KDE-2 IDL methods
virtual QCString TranslatorEnglish::trProperties()
Used as a section header for IDL properties
virtual QCString TranslatorEnglish::trPropertyDocumentation()
Used as a section header for IDL property documentation
virtual QCString TranslatorEnglish::trClasses()
Used for Java classes in the summary section of Java packages
virtual QCString TranslatorEnglish::trPackage(const char *name)
Used as the title of a Java package
virtual QCString TranslatorEnglish::trPackageList()
Title of the package index page
virtual QCString TranslatorEnglish::trPackageListDescription()
The description of the package index page
virtual QCString TranslatorEnglish::trPackages()
The link name in the Quick links header for each page
virtual QCString TranslatorEnglish::trDefineValue()
Text shown before a multi-line define
virtual QCString TranslatorEnglish::trBug()
Used as a marker that is put before a \bug item
virtual QCString TranslatorEnglish::trBugList()
Used as the header of the bug list
virtual QCString TranslatorEnglish::trRTFansicp()
Used as ansicpg for RTF file The following table shows the correlation of Charset name, Charset Value and <pre> Codepage number: Charset Name Charset Value(hex) Codepage number ------------------------------------------------------ DEFAULT_CHARSET 1 (x01) SYMBOL_CHARSET 2 (x02) OEM_CHARSET 255 (xFF) ANSI_CHARSET 0 (x00) 1252 RUSSIAN_CHARSET 204 (xCC) 1251 EE_CHARSET 238 (xEE) 1250 GREEK_CHARSET 161 (xA1) 1253 TURKISH_CHARSET 162 (xA2) 1254 BALTIC_CHARSET 186 (xBA) 1257 HEBREW_CHARSET 177 (xB1) 1255 ARABIC _CHARSET 178 (xB2) 1256 SHIFTJIS_CHARSET 128 (x80) 932 HANGEUL_CHARSET 129 (x81) 949 GB2313_CHARSET 134 (x86) 936 CHINESEBIG5_CHARSET 136 (x88) 950 </pre>
virtual QCString TranslatorEnglish::trRTFCharSet()
Used as ansicpg for RTF fcharset trRTFansicp() for a table of possible values.
virtual QCString TranslatorEnglish::trRTFGeneralIndex()
Used as header RTF general index
virtual QCString TranslatorEnglish::trClass(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorEnglish::trFile(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorEnglish::trNamespace(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorEnglish::trGroup(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorEnglish::trPage(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorEnglish::trMember(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorEnglish::trGlobal(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorEnglish::trAuthor(bool first_capital, bool singular)
This text is generated when the \author command is used and for the author section in man pages.
virtual QCString TranslatorEnglish::trReferences()
This text is put before the list of members referenced by a member
virtual QCString TranslatorEnglish::trImplementedFromList(int numEntries)
used in member documentation blocks to produce a list of members that are implemented by this one.
References trWriteList.
virtual QCString TranslatorEnglish::trImplementedInList(int numEntries)
used in member documentation blocks to produce a list of all members that implement this abstract member.
References trWriteList.
virtual QCString TranslatorEnglish::trRTFTableOfContents()
used in RTF documentation as a heading for the Table of Contents.
virtual QCString TranslatorEnglish::trDeprecatedList()
Used as the header of the list of item that have been flagged deprecated
virtual QCString TranslatorEnglish::trEvents()
Used as a header for declaration section of the events found in a C# program
virtual QCString TranslatorEnglish::trEventDocumentation()
Header used for the documentation section of a class' events.
virtual QCString TranslatorEnglish::trPackageTypes()
Used as a heading for a list of Java class types with package scope.
virtual QCString TranslatorEnglish::trPackageMembers()
Used as a heading for a list of Java class functions with package scope.
virtual QCString TranslatorEnglish::trStaticPackageMembers()
Used as a heading for a list of static Java class functions with package scope.
virtual QCString TranslatorEnglish::trPackageAttribs()
Used as a heading for a list of Java class variables with package scope.
virtual QCString TranslatorEnglish::trStaticPackageAttribs()
Used as a heading for a list of static Java class variables with package scope.
virtual QCString TranslatorEnglish::trAll()
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
virtual QCString TranslatorEnglish::trCallGraph()
Put in front of the call graph for a function.
virtual QCString TranslatorEnglish::trSearchForIndex()
When the search engine is enabled this text is put in the header of each page before the field where one can enter the text to search for.
virtual QCString TranslatorEnglish::trSearchResultsTitle()
This string is used as the title for the page listing the search results.
virtual QCString TranslatorEnglish::trSearchResults(int numDocuments)
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
virtual QCString TranslatorEnglish::trSearchMatches()
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
virtual QCString TranslatorEnglish::trSourceFile(QCString &filename)
This is used in HTML as the title of page with source code for file filename
virtual QCString TranslatorEnglish::trDirIndex()
This is used as the name of the chapter containing the directory hierarchy.
virtual QCString TranslatorEnglish::trDirDocumentation()
This is used as the name of the chapter containing the documentation of the directories.
virtual QCString TranslatorEnglish::trDirectories()
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
virtual QCString TranslatorEnglish::trDirDescription()
This returns a sentences that introduces the directory hierarchy. and the fact that it is sorted alphabetically per level
virtual QCString TranslatorEnglish::trDirReference(const char *dirName)
This returns the title of a directory page. The name of the directory is passed via dirName.
virtual QCString TranslatorEnglish::trDir(bool first_capital, bool singular)
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
virtual QCString TranslatorEnglish::trOverloadText()
This text is added to the documentation when the \overload command is used for a overloaded function.
virtual QCString TranslatorEnglish::trCallerGraph()
This is used to introduce a caller (or called-by) graph
virtual QCString TranslatorEnglish::trEnumerationValueDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
virtual QCString TranslatorEnglish::trMemberFunctionDocumentationFortran()
header that is put before the list of member subprograms (Fortran).
virtual QCString TranslatorEnglish::trCompoundListFortran()
This is put above each page as a link to the list of annotated data types (Fortran).
virtual QCString TranslatorEnglish::trCompoundMembersFortran()
This is put above each page as a link to all members of compounds (Fortran).
virtual QCString TranslatorEnglish::trCompoundListDescriptionFortran()
This is an introduction to the annotated compound list (Fortran).
virtual QCString TranslatorEnglish::trCompoundMembersDescriptionFortran(bool extractAll)
This is an introduction to the page with all data types (Fortran).
virtual QCString TranslatorEnglish::trCompoundIndexFortran()
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
virtual QCString TranslatorEnglish::trTypeDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
virtual QCString TranslatorEnglish::trSubprograms()
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
virtual QCString TranslatorEnglish::trSubprogramDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
virtual QCString TranslatorEnglish::trDataTypes()
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
virtual QCString TranslatorEnglish::trModulesList()
used as the title of page containing all the index of all modules (Fortran).
virtual QCString TranslatorEnglish::trModulesListDescription(bool extractAll)
used as an introduction to the modules list (Fortran)
virtual QCString TranslatorEnglish::trCompoundReferenceFortran(const char *clName, ClassDef::CompoundType compType, bool isTemplate)
used as the title of the HTML page of a module/type (Fortran)
virtual QCString TranslatorEnglish::trModuleReference(const char *namespaceName)
used as the title of the HTML page of a module (Fortran)
virtual QCString TranslatorEnglish::trModulesMembers()
This is put above each page as a link to all members of modules. (Fortran)
virtual QCString TranslatorEnglish::trModulesMemberDescription(bool extractAll)
This is an introduction to the page with all modules members (Fortran)
virtual QCString TranslatorEnglish::trModulesIndex()
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
virtual QCString TranslatorEnglish::trModule(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorEnglish::trGeneratedFromFilesFortran(ClassDef::CompoundType compType, bool single)
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
virtual QCString TranslatorEnglish::trType(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorEnglish::trSubprogram(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorEnglish::trTypeConstraints()
C# Type Constraint list
virtual QCString TranslatorEnglish::trDirRelation(const char *name)
directory relation for name
virtual QCString TranslatorEnglish::trLoading()
Loading message shown when loading search results
virtual QCString TranslatorEnglish::trGlobalNamespace()
Label used for search results in the global namespace
virtual QCString TranslatorEnglish::trSearching()
Message shown while searching
virtual QCString TranslatorEnglish::trNoMatches()
Text shown when no search results are found
virtual QCString TranslatorEnglish::trDirDependency(const char *name)
introduction text for the directory dependency graph
virtual QCString TranslatorEnglish::trFileIn(const char *name)
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
virtual QCString TranslatorEnglish::trIncludesFileIn(const char *name)
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
virtual QCString TranslatorEnglish::trDateTime(int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
Compiles a date string.
year Year in 4 digits month Month of the year: 1=January day Day of the Month: 1..31 dayOfWeek Day of the week: 1=Monday..7=Sunday hour Hour of the day: 0..23 minutes Minutes in the hour: 0..59 seconds Seconds within the minute: 0..59 includeTime Include time in the result string?
virtual QCString TranslatorEnglish::trCiteReferences()
Header for the page with bibliographic citations
virtual QCString TranslatorEnglish::trCopyright()
Text for copyright paragraph
virtual QCString TranslatorEnglish::trDirDepGraph(const char *name)
Header for the graph showing the directory dependencies
virtual QCString TranslatorEnglish::trDetailLevel()
Detail level selector shown for hierarchical indices
virtual QCString TranslatorEnglish::trTemplateParameters()
Section header for list of template parameters
virtual QCString TranslatorEnglish::trAndMore(const QCString &number)
Used in dot graph when UML_LOOK is enabled and there are many fields
virtual QCString TranslatorEnglish::trEnumGeneratedFromFiles(bool single)
Used file list for a Java enum
virtual QCString TranslatorEnglish::trEnumReference(const char *name)
Header of a Java enum page (Java enums are represented as classes).
virtual QCString TranslatorEnglish::trInheritedFrom(const char *members, const char *what)
Used for a section containing inherited members
virtual QCString TranslatorEnglish::trAdditionalInheritedMembers()
Header of the sections with inherited members specific for the base class(es)
virtual QCString TranslatorEnglish::trPanelSynchronisationTooltip(bool enable)
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
virtual QCString TranslatorEnglish::trProvidedByCategory()
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
virtual QCString TranslatorEnglish::trExtendsClass()
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
virtual QCString TranslatorEnglish::trClassMethods()
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
virtual QCString TranslatorEnglish::trInstanceMethods()
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
virtual QCString TranslatorEnglish::trMethodDocumentation()
Used as the header of the member functions of an Objective-C class.
virtual QCString TranslatorEnglish::trDesignOverview()
Used as the title of the design overview picture created for the VHDL output.
virtual QCString TranslatorEnglish::trInterfaces()
old style UNO IDL services: implemented interfaces
virtual QCString TranslatorEnglish::trServices()
old style UNO IDL services: inherited services
virtual QCString TranslatorEnglish::trConstantGroups()
UNO IDL constant groups.
virtual QCString TranslatorEnglish::trConstantGroupReference(const char *namespaceName)
UNO IDL constant groups.
virtual QCString TranslatorEnglish::trServiceReference(const char *sName)
UNO IDL service page title.
virtual QCString TranslatorEnglish::trSingletonReference(const char *sName)
UNO IDL singleton page title.
virtual QCString TranslatorEnglish::trServiceGeneratedFromFiles(bool single)
UNO IDL service page.
virtual QCString TranslatorEnglish::trSingletonGeneratedFromFiles(bool single)
UNO IDL singleton page.