Translator
const char Translator::Win1250ToISO88592Tab[]
The translation table used by Win1250ToISO88592() method.
const char Translator::ISO88592ToWin1250Tab[]
The translation table used by ISO88592ToWin1250() method.
const unsigned char Translator::Koi8RToWindows1251Tab[128]
The translation table used by Koi8RToWindows1251() method.
const unsigned char Translator::Windows1251ToKoi8RTab[128]
The translation table used by Windows1251ToKoi8R() method.
QCString Translator::Win1250ToISO88592(const QCString &sInput)
Returns the string converted from windows-1250 to iso-8859-2.
QCString Translator::ISO88592ToWin1250(const QCString &sInput)
Returns the string converted from iso-8859-2 to windows-1250.returns the string converted from iso-8859-2 to windows-1250
QCString Translator::Koi8RToWindows1251(const QCString &sInput)
Returns the string converted from koi8-r to windows-1251.
QCString Translator::Windows1251ToKoi8R(const QCString &sInput)
Returns the string converted from windows-1251 to koi8-r.returns the string converted from Windows-1251 to koi8-r
QCString Translator::JapaneseEucToSjis(const QCString &sInput)
Returns the string converted from Japanese-EUC to SJIS.returns the string converted from Japanese-EUC to SJIS
References euc2sjis.
virtual QCString Translator::updateNeededMessage()
This method is used to provide warning message that is displayed if the user chooses a language whose translation is not up to date. It is implemented by the adapter classes.
Referenced by TranslatorDecoder::updateNeededMessage.
virtual Translator::~Translator()
virtual QCString Translator::idLanguage()=0
virtual QCString Translator::latexLanguageSupportCommand()=0
virtual QCString Translator::idLanguageCharset()=0
virtual QCString Translator::trRelatedFunctions()=0
virtual QCString Translator::trRelatedSubscript()=0
virtual QCString Translator::trDetailedDescription()=0
virtual QCString Translator::trMemberTypedefDocumentation()=0
virtual QCString Translator::trMemberEnumerationDocumentation()=0
virtual QCString Translator::trMemberFunctionDocumentation()=0
virtual QCString Translator::trMemberDataDocumentation()=0
virtual QCString Translator::trMore()=0
virtual QCString Translator::trListOfAllMembers()=0
virtual QCString Translator::trMemberList()=0
virtual QCString Translator::trThisIsTheListOfAllMembers()=0
virtual QCString Translator::trIncludingInheritedMembers()=0
virtual QCString Translator::trGeneratedAutomatically(const char *s)=0
virtual QCString Translator::trEnumName()=0
virtual QCString Translator::trEnumValue()=0
virtual QCString Translator::trDefinedIn()=0
virtual QCString Translator::trModules()=0
virtual QCString Translator::trClassHierarchy()=0
virtual QCString Translator::trCompoundList()=0
virtual QCString Translator::trFileList()=0
virtual QCString Translator::trCompoundMembers()=0
virtual QCString Translator::trFileMembers()=0
virtual QCString Translator::trRelatedPages()=0
virtual QCString Translator::trExamples()=0
virtual QCString Translator::trSearch()=0
virtual QCString Translator::trClassHierarchyDescription()=0
virtual QCString Translator::trFileListDescription(bool extractAll)=0
virtual QCString Translator::trCompoundListDescription()=0
virtual QCString Translator::trCompoundMembersDescription(bool extractAll)=0
virtual QCString Translator::trFileMembersDescription(bool extractAll)=0
virtual QCString Translator::trExamplesDescription()=0
virtual QCString Translator::trRelatedPagesDescription()=0
virtual QCString Translator::trModulesDescription()=0
virtual QCString Translator::trDocumentation()=0
virtual QCString Translator::trModuleIndex()=0
virtual QCString Translator::trHierarchicalIndex()=0
virtual QCString Translator::trCompoundIndex()=0
virtual QCString Translator::trFileIndex()=0
virtual QCString Translator::trModuleDocumentation()=0
virtual QCString Translator::trClassDocumentation()=0
virtual QCString Translator::trFileDocumentation()=0
virtual QCString Translator::trExampleDocumentation()=0
virtual QCString Translator::trPageDocumentation()=0
virtual QCString Translator::trReferenceManual()=0
virtual QCString Translator::trDefines()=0
virtual QCString Translator::trFuncProtos()=0
virtual QCString Translator::trTypedefs()=0
virtual QCString Translator::trEnumerations()=0
virtual QCString Translator::trFunctions()=0
virtual QCString Translator::trVariables()=0
virtual QCString Translator::trEnumerationValues()=0
virtual QCString Translator::trDefineDocumentation()=0
virtual QCString Translator::trFunctionPrototypeDocumentation()=0
virtual QCString Translator::trTypedefDocumentation()=0
virtual QCString Translator::trEnumerationTypeDocumentation()=0
virtual QCString Translator::trFunctionDocumentation()=0
virtual QCString Translator::trVariableDocumentation()=0
virtual QCString Translator::trCompounds()=0
virtual QCString Translator::trGeneratedAt(const char *date, const char *projName)=0
virtual QCString Translator::trWrittenBy()=0
virtual QCString Translator::trClassDiagram(const char *clName)=0
virtual QCString Translator::trForInternalUseOnly()=0
virtual QCString Translator::trWarning()=0
virtual QCString Translator::trVersion()=0
virtual QCString Translator::trDate()=0
virtual QCString Translator::trReturns()=0
virtual QCString Translator::trSeeAlso()=0
virtual QCString Translator::trParameters()=0
virtual QCString Translator::trExceptions()=0
virtual QCString Translator::trGeneratedBy()=0
virtual QCString Translator::trNamespaceList()=0
virtual QCString Translator::trNamespaceListDescription(bool extractAll)=0
virtual QCString Translator::trFriends()=0
virtual QCString Translator::trRelatedFunctionDocumentation()=0
virtual QCString Translator::trCompoundReference(const char *clName, ClassDef::CompoundType compType, bool isTemplate)=0
virtual QCString Translator::trFileReference(const char *fileName)=0
virtual QCString Translator::trNamespaceReference(const char *namespaceName)=0
virtual QCString Translator::trPublicMembers()=0
virtual QCString Translator::trPublicSlots()=0
virtual QCString Translator::trSignals()=0
virtual QCString Translator::trStaticPublicMembers()=0
virtual QCString Translator::trProtectedMembers()=0
virtual QCString Translator::trProtectedSlots()=0
virtual QCString Translator::trStaticProtectedMembers()=0
virtual QCString Translator::trPrivateMembers()=0
virtual QCString Translator::trPrivateSlots()=0
virtual QCString Translator::trStaticPrivateMembers()=0
virtual QCString Translator::trWriteList(int numEntries)=0
virtual QCString Translator::trInheritsList(int numEntries)=0
virtual QCString Translator::trInheritedByList(int numEntries)=0
virtual QCString Translator::trReimplementedFromList(int numEntries)=0
virtual QCString Translator::trReimplementedInList(int numEntries)=0
virtual QCString Translator::trNamespaceMembers()=0
virtual QCString Translator::trNamespaceMemberDescription(bool extractAll)=0
virtual QCString Translator::trNamespaceIndex()=0
virtual QCString Translator::trNamespaceDocumentation()=0
virtual QCString Translator::trNamespaces()=0
virtual QCString Translator::trGeneratedFromFiles(ClassDef::CompoundType compType, bool single)=0
virtual QCString Translator::trAlphabeticalList()=0
virtual QCString Translator::trReturnValues()=0
virtual QCString Translator::trMainPage()=0
virtual QCString Translator::trPageAbbreviation()=0
virtual QCString Translator::trDefinedAtLineInSourceFile()=0
virtual QCString Translator::trDefinedInSourceFile()=0
virtual QCString Translator::trDeprecated()=0
virtual QCString Translator::trCollaborationDiagram(const char *clName)=0
virtual QCString Translator::trInclDepGraph(const char *fName)=0
virtual QCString Translator::trConstructorDocumentation()=0
virtual QCString Translator::trGotoSourceCode()=0
virtual QCString Translator::trGotoDocumentation()=0
virtual QCString Translator::trPrecondition()=0
virtual QCString Translator::trPostcondition()=0
virtual QCString Translator::trInvariant()=0
virtual QCString Translator::trInitialValue()=0
virtual QCString Translator::trCode()=0
virtual QCString Translator::trGraphicalHierarchy()=0
virtual QCString Translator::trGotoGraphicalHierarchy()=0
virtual QCString Translator::trGotoTextualHierarchy()=0
virtual QCString Translator::trPageIndex()=0
virtual QCString Translator::trNote()=0
virtual QCString Translator::trPublicTypes()=0
virtual QCString Translator::trPublicAttribs()=0
virtual QCString Translator::trStaticPublicAttribs()=0
virtual QCString Translator::trProtectedTypes()=0
virtual QCString Translator::trProtectedAttribs()=0
virtual QCString Translator::trStaticProtectedAttribs()=0
virtual QCString Translator::trPrivateTypes()=0
virtual QCString Translator::trPrivateAttribs()=0
virtual QCString Translator::trStaticPrivateAttribs()=0
virtual QCString Translator::trTodo()=0
virtual QCString Translator::trTodoList()=0
virtual QCString Translator::trReferencedBy()=0
virtual QCString Translator::trRemarks()=0
virtual QCString Translator::trAttention()=0
virtual QCString Translator::trInclByDepGraph()=0
virtual QCString Translator::trSince()=0
virtual QCString Translator::trLegendTitle()=0
virtual QCString Translator::trLegendDocs()=0
virtual QCString Translator::trLegend()=0
virtual QCString Translator::trTest()=0
virtual QCString Translator::trTestList()=0
virtual QCString Translator::trDCOPMethods()=0
virtual QCString Translator::trProperties()=0
virtual QCString Translator::trPropertyDocumentation()=0
virtual QCString Translator::trClasses()=0
virtual QCString Translator::trPackage(const char *name)=0
virtual QCString Translator::trPackageList()=0
virtual QCString Translator::trPackageListDescription()=0
virtual QCString Translator::trPackages()=0
virtual QCString Translator::trDefineValue()=0
virtual QCString Translator::trBug()=0
virtual QCString Translator::trBugList()=0
virtual QCString Translator::trRTFansicp()=0
Used as ansicpg for RTF file The following table shows the correlation of Charset name, Charset Value and <pre> Codepage number: Charset Name Charset Value(hex) Codepage number ------------------------------------------------------ DEFAULT_CHARSET 1 (x01) SYMBOL_CHARSET 2 (x02) OEM_CHARSET 255 (xFF) ANSI_CHARSET 0 (x00) 1252 RUSSIAN_CHARSET 204 (xCC) 1251 EE_CHARSET 238 (xEE) 1250 GREEK_CHARSET 161 (xA1) 1253 TURKISH_CHARSET 162 (xA2) 1254 BALTIC_CHARSET 186 (xBA) 1257 HEBREW_CHARSET 177 (xB1) 1255 ARABIC _CHARSET 178 (xB2) 1256 SHIFTJIS_CHARSET 128 (x80) 932 HANGEUL_CHARSET 129 (x81) 949 GB2313_CHARSET 134 (x86) 936 CHINESEBIG5_CHARSET 136 (x88) 950 </pre>
Referenced by TranslatorDecoder::trRTFansicp.
virtual QCString Translator::trRTFCharSet()=0
Character sets 0 ANSI 1 Default 2 Symbol 3 Invalid 77 Mac 128 Shift Jis 129 Hangul 130 Johab 134 GB2312 136 Big5 161 Greek 162 Turkish 163 Vietnamese 177 Hebrew 178 Arabic 179 Arabic Traditional 180 Arabic user 181 Hebrew user 186 Baltic 204 Russian 222 Thai 238 Eastern European 254 PC 437 255 OEM
Referenced by TranslatorDecoder::trRTFCharSet.
virtual QCString Translator::trRTFGeneralIndex()=0
virtual QCString Translator::trClass(bool first_capital, bool singular)=0
virtual QCString Translator::trFile(bool first_capital, bool singular)=0
virtual QCString Translator::trNamespace(bool first_capital, bool singular)=0
virtual QCString Translator::trGroup(bool first_capital, bool singular)=0
virtual QCString Translator::trPage(bool first_capital, bool singular)=0
virtual QCString Translator::trMember(bool first_capital, bool singular)=0
virtual QCString Translator::trGlobal(bool first_capital, bool singular)=0
virtual QCString Translator::trAuthor(bool first_capital, bool singular)=0
virtual QCString Translator::trReferences()=0
virtual QCString Translator::trImplementedFromList(int numEntries)=0
virtual QCString Translator::trImplementedInList(int numEntries)=0
virtual QCString Translator::trRTFTableOfContents()=0
virtual QCString Translator::trDeprecatedList()=0
virtual QCString Translator::trEvents()=0
virtual QCString Translator::trEventDocumentation()=0
virtual QCString Translator::trPackageTypes()=0
virtual QCString Translator::trPackageMembers()=0
virtual QCString Translator::trStaticPackageMembers()=0
virtual QCString Translator::trPackageAttribs()=0
virtual QCString Translator::trStaticPackageAttribs()=0
virtual QCString Translator::trAll()=0
virtual QCString Translator::trCallGraph()=0
virtual QCString Translator::trSearchForIndex()=0
virtual QCString Translator::trSearchResultsTitle()=0
virtual QCString Translator::trSearchResults(int numDocuments)=0
virtual QCString Translator::trSearchMatches()=0
virtual QCString Translator::trSourceFile(QCString &filename)=0
virtual QCString Translator::trDirIndex()=0
virtual QCString Translator::trDirDocumentation()=0
virtual QCString Translator::trDirectories()=0
virtual QCString Translator::trDirDescription()=0
virtual QCString Translator::trDirReference(const char *dirName)=0
virtual QCString Translator::trDir(bool first_capital, bool singular)=0
virtual QCString Translator::trOverloadText()=0
virtual QCString Translator::trCallerGraph()=0
virtual QCString Translator::trEnumerationValueDocumentation()=0
virtual QCString Translator::trMemberFunctionDocumentationFortran()=0
virtual QCString Translator::trCompoundListFortran()=0
virtual QCString Translator::trCompoundMembersFortran()=0
virtual QCString Translator::trCompoundListDescriptionFortran()=0
virtual QCString Translator::trCompoundMembersDescriptionFortran(bool extractAll)=0
virtual QCString Translator::trCompoundIndexFortran()=0
virtual QCString Translator::trTypeDocumentation()=0
virtual QCString Translator::trSubprograms()=0
virtual QCString Translator::trSubprogramDocumentation()=0
virtual QCString Translator::trDataTypes()=0
virtual QCString Translator::trModulesList()=0
virtual QCString Translator::trModulesListDescription(bool extractAll)=0
virtual QCString Translator::trCompoundReferenceFortran(const char *clName, ClassDef::CompoundType compType, bool isTemplate)=0
virtual QCString Translator::trModuleReference(const char *namespaceName)=0
virtual QCString Translator::trModulesMembers()=0
virtual QCString Translator::trModulesMemberDescription(bool extractAll)=0
virtual QCString Translator::trModulesIndex()=0
virtual QCString Translator::trModule(bool first_capital, bool singular)=0
virtual QCString Translator::trGeneratedFromFilesFortran(ClassDef::CompoundType compType, bool single)=0
virtual QCString Translator::trType(bool first_capital, bool singular)=0
virtual QCString Translator::trSubprogram(bool first_capital, bool singular)=0
virtual QCString Translator::trTypeConstraints()=0
virtual QCString Translator::trDirRelation(const char *name)=0
virtual QCString Translator::trLoading()=0
virtual QCString Translator::trGlobalNamespace()=0
virtual QCString Translator::trSearching()=0
virtual QCString Translator::trNoMatches()=0
virtual QCString Translator::trDirDependency(const char *name)=0
virtual QCString Translator::trFileIn(const char *name)=0
virtual QCString Translator::trIncludesFileIn(const char *name)=0
virtual QCString Translator::trDateTime(int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)=0
virtual QCString Translator::trCiteReferences()=0
virtual QCString Translator::trCopyright()=0
virtual QCString Translator::trDirDepGraph(const char *name)=0
virtual QCString Translator::trDetailLevel()=0
virtual QCString Translator::trTemplateParameters()=0
virtual QCString Translator::trAndMore(const QCString &number)=0
virtual QCString Translator::trEnumGeneratedFromFiles(bool single)=0
virtual QCString Translator::trEnumReference(const char *name)=0
virtual QCString Translator::trInheritedFrom(const char *members, const char *what)=0
virtual QCString Translator::trAdditionalInheritedMembers()=0
virtual QCString Translator::trPanelSynchronisationTooltip(bool enable)=0
virtual QCString Translator::trProvidedByCategory()=0
virtual QCString Translator::trExtendsClass()=0
virtual QCString Translator::trClassMethods()=0
virtual QCString Translator::trInstanceMethods()=0
virtual QCString Translator::trMethodDocumentation()=0
virtual QCString Translator::trDesignOverview()=0
virtual QCString Translator::trInterfaces()=0
virtual QCString Translator::trServices()=0
virtual QCString Translator::trConstantGroups()=0
virtual QCString Translator::trConstantGroupReference(const char *namespaceName)=0
virtual QCString Translator::trServiceReference(const char *sName)=0
virtual QCString Translator::trSingletonReference(const char *sName)=0
virtual QCString Translator::trServiceGeneratedFromFiles(bool single)=0
virtual QCString Translator::trSingletonGeneratedFromFiles(bool single)=0