ParserInterface
virtual ParserInterface::~ParserInterface()
virtual void ParserInterface::startTranslationUnit(const char *fileName)=0
Starts processing a translation unit (source files + headers).
After this call parseInput() is called with sameTranslationUnit set to FALSE. If parseInput() returns additional include files, these are also processed using parseInput() with sameTranslationUnit set to TRUE. After that finishTranslationUnit() is called.
virtual void ParserInterface::finishTranslationUnit()=0
Called after all files in a translation unit have been processed.
virtual void ParserInterface::parseInput(const char *fileName, const char *fileBuf, Entry *root, bool sameTranslationUnit, QStrList &filesInSameTranslationUnit)=0
Parses a single input file with the goal to build an Entry tree.
fileName The full name of the file. fileBuf The contents of the file (zero terminated). root The root of the tree of Entry *nodes representing the information extracted from the file. sameTranslationUnit TRUE if this file was found in the same translation unit (in the filesInSameTranslationUnit list returned for another file). filesInSameTranslationUnit other files expected to be found in the same translation unit (used for libclang)
virtual bool ParserInterface::needsPreprocessing(const QCString &extension)=0
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
parseInput()
virtual void ParserInterface::parseCode(CodeOutputInterface &codeOutIntf, const char *scopeName, const QCString &input, bool isExampleBlock, const char *exampleName=0, FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, MemberDef *memberDef=0, bool showLineNumbers=TRUE, Definition *searchCtx=0)=0
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
codeOutIntf Abstract interface for writing the result. scopeName Name of scope to which the code belongs. input Actual code in the form of a string isExampleBlock TRUE iff the code is part of an example. exampleName Name of the example. fileDef File definition to which the code is associated. startLine Starting line in case of a code fragment. endLine Ending line of the code fragment. inlineFragment Code fragment that is to be shown inline as part of the documentation. memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member). showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragement searchCtx context under which search data has to be stored.
Referenced by MarkdownFileParser::parseCode, MemberDef::writeDocumentation, Definition::writeInlineCode, FileDef::writeSource.
virtual void ParserInterface::resetCodeParserState()=0
Resets the state of the code parser.
Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state. parseCode()
Referenced by MarkdownFileParser::resetCodeParserState, MemberDef::writeDocumentation, Definition::writeInlineCode, FileDef::writeSource.
virtual void ParserInterface::parsePrototype(const char *text)=0
Callback function called by the comment block scanner.
It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Referenced by MarkdownFileParser::parsePrototype.