TranslatorAfrikaans
virtual QCString TranslatorAfrikaans::idLanguage()
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
virtual QCString TranslatorAfrikaans::latexLanguageSupportCommand()
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example "\\usepackage[german]{babel}\n" or "\\usepackage{polski}\n" "\\usepackage[latin2]{inputenc}\n" "\\usepackage[T1]{fontenc}\n" The Afrikaans LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
virtual QCString TranslatorAfrikaans::idLanguageCharset()
return the language charset. This will be used for the HTML output
virtual QCString TranslatorAfrikaans::trRelatedFunctions()
used in the compound documentation before a list of related functions.
virtual QCString TranslatorAfrikaans::trRelatedSubscript()
subscript for the related functions.
virtual QCString TranslatorAfrikaans::trDetailedDescription()
header that is put before the detailed description of files, classes and namespaces.
virtual QCString TranslatorAfrikaans::trMemberTypedefDocumentation()
header that is put before the list of typedefs.
virtual QCString TranslatorAfrikaans::trMemberEnumerationDocumentation()
header that is put before the list of enumerations.
virtual QCString TranslatorAfrikaans::trMemberFunctionDocumentation()
header that is put before the list of member functions.
virtual QCString TranslatorAfrikaans::trMemberDataDocumentation()
header that is put before the list of member attributes.
virtual QCString TranslatorAfrikaans::trMore()
this is the text of a link put after brief descriptions.
virtual QCString TranslatorAfrikaans::trListOfAllMembers()
put in the class documentation
virtual QCString TranslatorAfrikaans::trMemberList()
used as the title of the "list of all members" page of a class
virtual QCString TranslatorAfrikaans::trThisIsTheListOfAllMembers()
this is the first part of a sentence that is followed by a class name
virtual QCString TranslatorAfrikaans::trIncludingInheritedMembers()
this is the remainder of the sentence after the class name
virtual QCString TranslatorAfrikaans::trGeneratedAutomatically(const char *s)
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
virtual QCString TranslatorAfrikaans::trEnumName()
put after an enum name in the list of all members
virtual QCString TranslatorAfrikaans::trEnumValue()
put after an enum value in the list of all members
virtual QCString TranslatorAfrikaans::trDefinedIn()
put after an undocumented member in the list of all members
virtual QCString TranslatorAfrikaans::trModules()
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
virtual QCString TranslatorAfrikaans::trClassHierarchy()
This is put above each page as a link to the class hierarchy
virtual QCString TranslatorAfrikaans::trCompoundList()
This is put above each page as a link to the list of annotated classes
virtual QCString TranslatorAfrikaans::trFileList()
This is put above each page as a link to the list of documented files
virtual QCString TranslatorAfrikaans::trCompoundMembers()
This is put above each page as a link to all members of compounds.
virtual QCString TranslatorAfrikaans::trFileMembers()
This is put above each page as a link to all members of files.
virtual QCString TranslatorAfrikaans::trRelatedPages()
This is put above each page as a link to all related pages.
virtual QCString TranslatorAfrikaans::trExamples()
This is put above each page as a link to all examples.
virtual QCString TranslatorAfrikaans::trSearch()
This is put above each page as a link to the search engine.
virtual QCString TranslatorAfrikaans::trClassHierarchyDescription()
This is an introduction to the class hierarchy.
virtual QCString TranslatorAfrikaans::trFileListDescription(bool extractAll)
This is an introduction to the list with all files.
virtual QCString TranslatorAfrikaans::trCompoundListDescription()
This is an introduction to the annotated compound list.
virtual QCString TranslatorAfrikaans::trCompoundMembersDescription(bool extractAll)
This is an introduction to the page with all class members.
virtual QCString TranslatorAfrikaans::trFileMembersDescription(bool extractAll)
This is an introduction to the page with all file members.
virtual QCString TranslatorAfrikaans::trExamplesDescription()
This is an introduction to the page with the list of all examples
virtual QCString TranslatorAfrikaans::trRelatedPagesDescription()
This is an introduction to the page with the list of related pages
virtual QCString TranslatorAfrikaans::trModulesDescription()
This is an introduction to the page with the list of class/file groups
virtual QCString TranslatorAfrikaans::trDocumentation()
This is used in HTML as the title of index.html.
virtual QCString TranslatorAfrikaans::trModuleIndex()
This is used in LaTeX as the title of the chapter with the index of all groups.
virtual QCString TranslatorAfrikaans::trHierarchicalIndex()
This is used in LaTeX as the title of the chapter with the class hierarchy.
virtual QCString TranslatorAfrikaans::trCompoundIndex()
This is used in LaTeX as the title of the chapter with the annotated compound index.
virtual QCString TranslatorAfrikaans::trFileIndex()
This is used in LaTeX as the title of the chapter with the list of all files.
virtual QCString TranslatorAfrikaans::trModuleDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
virtual QCString TranslatorAfrikaans::trClassDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
virtual QCString TranslatorAfrikaans::trFileDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all files.
virtual QCString TranslatorAfrikaans::trExampleDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
virtual QCString TranslatorAfrikaans::trPageDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all related pages.
virtual QCString TranslatorAfrikaans::trReferenceManual()
This is used in LaTeX as the title of the document
virtual QCString TranslatorAfrikaans::trDefines()
This is used in the documentation of a file as a header before the list of defines
virtual QCString TranslatorAfrikaans::trFuncProtos()
This is used in the documentation of a file as a header before the list of function prototypes
virtual QCString TranslatorAfrikaans::trTypedefs()
This is used in the documentation of a file as a header before the list of typedefs
virtual QCString TranslatorAfrikaans::trEnumerations()
This is used in the documentation of a file as a header before the list of enumerations
virtual QCString TranslatorAfrikaans::trFunctions()
This is used in the documentation of a file as a header before the list of (global) functions
virtual QCString TranslatorAfrikaans::trVariables()
This is used in the documentation of a file as a header before the list of (global) variables
virtual QCString TranslatorAfrikaans::trEnumerationValues()
This is used in the documentation of a file as a header before the list of (global) variables
virtual QCString TranslatorAfrikaans::trDefineDocumentation()
This is used in the documentation of a file before the list of documentation blocks for defines
virtual QCString TranslatorAfrikaans::trFunctionPrototypeDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for function prototypes
virtual QCString TranslatorAfrikaans::trTypedefDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
virtual QCString TranslatorAfrikaans::trEnumerationTypeDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
virtual QCString TranslatorAfrikaans::trFunctionDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
virtual QCString TranslatorAfrikaans::trVariableDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
virtual QCString TranslatorAfrikaans::trCompounds()
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
virtual QCString TranslatorAfrikaans::trGeneratedAt(const char *date, const char *projName)
This is used in the standard footer of each page and indicates when the page was generated
virtual QCString TranslatorAfrikaans::trWrittenBy()
This is part of the sentence used in the standard footer of each page.
virtual QCString TranslatorAfrikaans::trClassDiagram(const char *clName)
this text is put before a class diagram
virtual QCString TranslatorAfrikaans::trForInternalUseOnly()
this text is generated when the \internal command is used.
virtual QCString TranslatorAfrikaans::trWarning()
this text is generated when the \warning command is used.
virtual QCString TranslatorAfrikaans::trVersion()
this text is generated when the \version command is used.
virtual QCString TranslatorAfrikaans::trDate()
this text is generated when the \date command is used.
virtual QCString TranslatorAfrikaans::trReturns()
this text is generated when the \return command is used.
virtual QCString TranslatorAfrikaans::trSeeAlso()
this text is generated when the \sa command is used.
virtual QCString TranslatorAfrikaans::trParameters()
this text is generated when the \param command is used.
virtual QCString TranslatorAfrikaans::trExceptions()
this text is generated when the \exception command is used.
virtual QCString TranslatorAfrikaans::trGeneratedBy()
this text is used in the title page of a LaTeX document.
virtual QCString TranslatorAfrikaans::trNamespaceList()
used as the title of page containing all the index of all namespaces.
virtual QCString TranslatorAfrikaans::trNamespaceListDescription(bool extractAll)
used as an introduction to the namespace list
virtual QCString TranslatorAfrikaans::trFriends()
used in the class documentation as a header before the list of all friends of a class
virtual QCString TranslatorAfrikaans::trRelatedFunctionDocumentation()
used in the class documentation as a header before the list of all related classes
virtual QCString TranslatorAfrikaans::trCompoundReference(const char *clName, ClassDef::CompoundType compType, bool isTemplate)
used as the title of the HTML page of a class/struct/union
virtual QCString TranslatorAfrikaans::trFileReference(const char *fileName)
used as the title of the HTML page of a file
virtual QCString TranslatorAfrikaans::trNamespaceReference(const char *namespaceName)
used as the title of the HTML page of a namespace
virtual QCString TranslatorAfrikaans::trPublicMembers()
virtual QCString TranslatorAfrikaans::trPublicSlots()
virtual QCString TranslatorAfrikaans::trSignals()
virtual QCString TranslatorAfrikaans::trStaticPublicMembers()
virtual QCString TranslatorAfrikaans::trProtectedMembers()
virtual QCString TranslatorAfrikaans::trProtectedSlots()
virtual QCString TranslatorAfrikaans::trStaticProtectedMembers()
virtual QCString TranslatorAfrikaans::trPrivateMembers()
virtual QCString TranslatorAfrikaans::trPrivateSlots()
virtual QCString TranslatorAfrikaans::trStaticPrivateMembers()
virtual QCString TranslatorAfrikaans::trWriteList(int numEntries)
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Referenced by trImplementedFromList, trImplementedInList, trInheritedByList, trInheritsList, trReimplementedFromList, trReimplementedInList.
virtual QCString TranslatorAfrikaans::trInheritsList(int numEntries)
used in class documentation to produce a list of base classes, if class diagrams are disabled.
References trWriteList.
virtual QCString TranslatorAfrikaans::trInheritedByList(int numEntries)
used in class documentation to produce a list of super classes, if class diagrams are disabled.
References trWriteList.
virtual QCString TranslatorAfrikaans::trReimplementedFromList(int numEntries)
used in member documentation blocks to produce a list of members that are hidden by this one.
References trWriteList.
virtual QCString TranslatorAfrikaans::trReimplementedInList(int numEntries)
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
References trWriteList.
virtual QCString TranslatorAfrikaans::trNamespaceMembers()
This is put above each page as a link to all members of namespaces.
virtual QCString TranslatorAfrikaans::trNamespaceMemberDescription(bool extractAll)
This is an introduction to the page with all namespace members
virtual QCString TranslatorAfrikaans::trNamespaceIndex()
This is used in LaTeX as the title of the chapter with the index of all namespaces.
virtual QCString TranslatorAfrikaans::trNamespaceDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
virtual QCString TranslatorAfrikaans::trNamespaces()
This is used in the documentation before the list of all namespaces in a file.
virtual QCString TranslatorAfrikaans::trGeneratedFromFiles(ClassDef::CompoundType compType, bool single)
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
virtual QCString TranslatorAfrikaans::trAlphabeticalList()
This is in the (quick) index as a link to the alphabetical compound list.
virtual QCString TranslatorAfrikaans::trReturnValues()
This is used as the heading text for the retval command.
virtual QCString TranslatorAfrikaans::trMainPage()
This is in the (quick) index as a link to the main page (index.html)
virtual QCString TranslatorAfrikaans::trPageAbbreviation()
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
virtual QCString TranslatorAfrikaans::trDefinedAtLineInSourceFile()
virtual QCString TranslatorAfrikaans::trDefinedInSourceFile()
virtual QCString TranslatorAfrikaans::trDeprecated()
virtual QCString TranslatorAfrikaans::trCollaborationDiagram(const char *clName)
this text is put before a collaboration diagram
virtual QCString TranslatorAfrikaans::trInclDepGraph(const char *fName)
this text is put before an include dependency graph
virtual QCString TranslatorAfrikaans::trConstructorDocumentation()
header that is put before the list of constructor/destructors.
virtual QCString TranslatorAfrikaans::trGotoSourceCode()
Used in the file documentation to point to the corresponding sources.
virtual QCString TranslatorAfrikaans::trGotoDocumentation()
Used in the file sources to point to the corresponding documentation.
virtual QCString TranslatorAfrikaans::trPrecondition()
Text for the \pre command
virtual QCString TranslatorAfrikaans::trPostcondition()
Text for the \post command
virtual QCString TranslatorAfrikaans::trInvariant()
Text for the \invariant command
virtual QCString TranslatorAfrikaans::trInitialValue()
Text shown before a multi-line variable/enum initialization
virtual QCString TranslatorAfrikaans::trCode()
Text used the source code in the file index
virtual QCString TranslatorAfrikaans::trGraphicalHierarchy()
virtual QCString TranslatorAfrikaans::trGotoGraphicalHierarchy()
virtual QCString TranslatorAfrikaans::trGotoTextualHierarchy()
virtual QCString TranslatorAfrikaans::trPageIndex()
virtual QCString TranslatorAfrikaans::trNote()
virtual QCString TranslatorAfrikaans::trPublicTypes()
virtual QCString TranslatorAfrikaans::trPublicAttribs()
virtual QCString TranslatorAfrikaans::trStaticPublicAttribs()
virtual QCString TranslatorAfrikaans::trProtectedTypes()
virtual QCString TranslatorAfrikaans::trProtectedAttribs()
virtual QCString TranslatorAfrikaans::trStaticProtectedAttribs()
virtual QCString TranslatorAfrikaans::trPrivateTypes()
virtual QCString TranslatorAfrikaans::trPrivateAttribs()
virtual QCString TranslatorAfrikaans::trStaticPrivateAttribs()
virtual QCString TranslatorAfrikaans::trTodo()
Used as a marker that is put before a \todo item
virtual QCString TranslatorAfrikaans::trTodoList()
Used as the header of the todo list
virtual QCString TranslatorAfrikaans::trReferencedBy()
virtual QCString TranslatorAfrikaans::trRemarks()
virtual QCString TranslatorAfrikaans::trAttention()
virtual QCString TranslatorAfrikaans::trInclByDepGraph()
virtual QCString TranslatorAfrikaans::trSince()
virtual QCString TranslatorAfrikaans::trLegendTitle()
title of the graph legend page
virtual QCString TranslatorAfrikaans::trLegendDocs()
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
virtual QCString TranslatorAfrikaans::trLegend()
text for the link to the legend page
virtual QCString TranslatorAfrikaans::trTest()
Used as a marker that is put before a test item
virtual QCString TranslatorAfrikaans::trTestList()
Used as the header of the test list
virtual QCString TranslatorAfrikaans::trDCOPMethods()
Used as a section header for KDE-2 IDL methods
virtual QCString TranslatorAfrikaans::trProperties()
Used as a section header for IDL properties
virtual QCString TranslatorAfrikaans::trPropertyDocumentation()
Used as a section header for IDL property documentation
virtual QCString TranslatorAfrikaans::trClasses()
Used for Java classes in the summary section of Java packages
virtual QCString TranslatorAfrikaans::trPackage(const char *name)
Used as the title of a Java package
virtual QCString TranslatorAfrikaans::trPackageList()
Title of the package index page
virtual QCString TranslatorAfrikaans::trPackageListDescription()
The description of the package index page
virtual QCString TranslatorAfrikaans::trPackages()
The link name in the Quick links header for each page
virtual QCString TranslatorAfrikaans::trDefineValue()
Text shown before a multi-line define
virtual QCString TranslatorAfrikaans::trBug()
Used as a marker that is put before a \bug item
virtual QCString TranslatorAfrikaans::trBugList()
Used as the header of the bug list
virtual QCString TranslatorAfrikaans::trRTFansicp()
Used as ansicpg for RTF file The following table shows the correlation of Charset name, Charset Value and <pre> Codepage number: Charset Name Charset Value(hex) Codepage number ------------------------------------------------------ DEFAULT_CHARSET 1 (x01) SYMBOL_CHARSET 2 (x02) OEM_CHARSET 255 (xFF) ANSI_CHARSET 0 (x00) 1252 RUSSIAN_CHARSET 204 (xCC) 1251 EE_CHARSET 238 (xEE) 1250 GREEK_CHARSET 161 (xA1) 1253 TURKISH_CHARSET 162 (xA2) 1254 BALTIC_CHARSET 186 (xBA) 1257 HEBREW_CHARSET 177 (xB1) 1255 ARABIC _CHARSET 178 (xB2) 1256 SHIFTJIS_CHARSET 128 (x80) 932 HANGEUL_CHARSET 129 (x81) 949 GB2313_CHARSET 134 (x86) 936 CHINESEBIG5_CHARSET 136 (x88) 950 </pre>
virtual QCString TranslatorAfrikaans::trRTFCharSet()
Used as ansicpg for RTF fcharset trRTFansicp() for a table of possible values.
virtual QCString TranslatorAfrikaans::trRTFGeneralIndex()
Used as header RTF general index
virtual QCString TranslatorAfrikaans::trClass(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorAfrikaans::trFile(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorAfrikaans::trNamespace(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorAfrikaans::trGroup(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorAfrikaans::trPage(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorAfrikaans::trMember(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorAfrikaans::trGlobal(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorAfrikaans::trAuthor(bool first_capital, bool singular)
This text is generated when the \author command is used and for the author section in man pages.
virtual QCString TranslatorAfrikaans::trReferences()
This text is put before the list of members referenced by a member
virtual QCString TranslatorAfrikaans::trImplementedFromList(int numEntries)
used in member documentation blocks to produce a list of members that are implemented by this one.
References trWriteList.
virtual QCString TranslatorAfrikaans::trImplementedInList(int numEntries)
used in member documentation blocks to produce a list of all members that implement this abstract member.
References trWriteList.
virtual QCString TranslatorAfrikaans::trRTFTableOfContents()
used in RTF documentation as a heading for the Table of Contents.
virtual QCString TranslatorAfrikaans::trDeprecatedList()
Used as the header of the list of item that have been flagged deprecated
virtual QCString TranslatorAfrikaans::trEvents()
Used as a header for declaration section of the events found in a C# program
virtual QCString TranslatorAfrikaans::trEventDocumentation()
Header used for the documentation section of a class' events.
virtual QCString TranslatorAfrikaans::trPackageTypes()
Used as a heading for a list of Java class types with package scope.
virtual QCString TranslatorAfrikaans::trPackageMembers()
Used as a heading for a list of Java class functions with package scope.
virtual QCString TranslatorAfrikaans::trStaticPackageMembers()
Used as a heading for a list of static Java class functions with package scope.
virtual QCString TranslatorAfrikaans::trPackageAttribs()
Used as a heading for a list of Java class variables with package scope.
virtual QCString TranslatorAfrikaans::trStaticPackageAttribs()
Used as a heading for a list of static Java class variables with package scope.
virtual QCString TranslatorAfrikaans::trAll()
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
virtual QCString TranslatorAfrikaans::trCallGraph()
Put in front of the call graph for a function.
virtual QCString TranslatorAfrikaans::trSearchForIndex()
When the search engine is enabled this text is put in the header of each page before the field where one can enter the text to search for.
virtual QCString TranslatorAfrikaans::trSearchResultsTitle()
This string is used as the title for the page listing the search results.
virtual QCString TranslatorAfrikaans::trSearchResults(int numDocuments)
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
virtual QCString TranslatorAfrikaans::trSearchMatches()
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
virtual QCString TranslatorAfrikaans::trSourceFile(QCString &filename)
This is used in HTML as the title of page with source code for file filename
virtual QCString TranslatorAfrikaans::trDirIndex()
This is used as the name of the chapter containing the directory hierarchy.
virtual QCString TranslatorAfrikaans::trDirDocumentation()
This is used as the name of the chapter containing the documentation of the directories.
virtual QCString TranslatorAfrikaans::trDirectories()
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
virtual QCString TranslatorAfrikaans::trDirDescription()
This returns a sentences that introduces the directory hierarchy. and the fact that it is sorted alphabetically per level
virtual QCString TranslatorAfrikaans::trDirReference(const char *dirName)
This returns the title of a directory page. The name of the directory is passed via dirName.
virtual QCString TranslatorAfrikaans::trDir(bool first_capital, bool singular)
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
virtual QCString TranslatorAfrikaans::trOverloadText()
This text is added to the documentation when the \overload command is used for a overloaded function.
virtual QCString TranslatorAfrikaans::trCallerGraph()
This is used to introduce a caller (or called-by) graph
virtual QCString TranslatorAfrikaans::trEnumerationValueDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
virtual QCString TranslatorAfrikaans::trMemberFunctionDocumentationFortran()
header that is put before the list of member subprograms (Fortran).
virtual QCString TranslatorAfrikaans::trCompoundListFortran()
This is put above each page as a link to the list of annotated data types (Fortran).
virtual QCString TranslatorAfrikaans::trCompoundMembersFortran()
This is put above each page as a link to all members of compounds (Fortran).
virtual QCString TranslatorAfrikaans::trCompoundListDescriptionFortran()
This is an introduction to the annotated compound list (Fortran).
virtual QCString TranslatorAfrikaans::trCompoundMembersDescriptionFortran(bool extractAll)
This is an introduction to the page with all data types (Fortran).
virtual QCString TranslatorAfrikaans::trCompoundIndexFortran()
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
virtual QCString TranslatorAfrikaans::trTypeDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
virtual QCString TranslatorAfrikaans::trSubprograms()
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
virtual QCString TranslatorAfrikaans::trSubprogramDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
virtual QCString TranslatorAfrikaans::trDataTypes()
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
virtual QCString TranslatorAfrikaans::trModulesList()
used as the title of page containing all the index of all modules (Fortran).
virtual QCString TranslatorAfrikaans::trModulesListDescription(bool extractAll)
used as an introduction to the modules list (Fortran)
virtual QCString TranslatorAfrikaans::trCompoundReferenceFortran(const char *clName, ClassDef::CompoundType compType, bool isTemplate)
used as the title of the HTML page of a module/type (Fortran)
virtual QCString TranslatorAfrikaans::trModuleReference(const char *namespaceName)
used as the title of the HTML page of a module (Fortran)
virtual QCString TranslatorAfrikaans::trModulesMembers()
This is put above each page as a link to all members of modules. (Fortran)
virtual QCString TranslatorAfrikaans::trModulesMemberDescription(bool extractAll)
This is an introduction to the page with all modules members (Fortran)
virtual QCString TranslatorAfrikaans::trModulesIndex()
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
virtual QCString TranslatorAfrikaans::trModule(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorAfrikaans::trGeneratedFromFilesFortran(ClassDef::CompoundType compType, bool single)
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
virtual QCString TranslatorAfrikaans::trType(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorAfrikaans::trSubprogram(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorAfrikaans::trTypeConstraints()
C# Type Constraint list