TranslatorSerbianCyrilic
virtual QCString TranslatorSerbianCyrilic::idLanguage()
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
virtual QCString TranslatorSerbianCyrilic::latexLanguageSupportCommand()
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example "\\usepackage[german]{babel}\n" or "\\usepackage{polski}\n" "\\usepackage[latin2]{inputenc}\n" "\\usepackage[T1]{fontenc}\n" The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
virtual QCString TranslatorSerbianCyrilic::idLanguageCharset()
return the language charset. This will be used for the HTML output
virtual QCString TranslatorSerbianCyrilic::trRelatedFunctions()
used in the compound documentation before a list of related functions.
virtual QCString TranslatorSerbianCyrilic::trRelatedSubscript()
subscript for the related functions.
virtual QCString TranslatorSerbianCyrilic::trDetailedDescription()
header that is put before the detailed description of files, classes and namespaces.
virtual QCString TranslatorSerbianCyrilic::trMemberTypedefDocumentation()
header that is put before the list of typedefs.
virtual QCString TranslatorSerbianCyrilic::trMemberEnumerationDocumentation()
header that is put before the list of enumerations.
virtual QCString TranslatorSerbianCyrilic::trMemberFunctionDocumentation()
header that is put before the list of member functions.
virtual QCString TranslatorSerbianCyrilic::trMemberDataDocumentation()
header that is put before the list of member attributes.
virtual QCString TranslatorSerbianCyrilic::trMore()
this is the text of a link put after brief descriptions.
virtual QCString TranslatorSerbianCyrilic::trListOfAllMembers()
put in the class documentation
virtual QCString TranslatorSerbianCyrilic::trMemberList()
used as the title of the "list of all members" page of a class
virtual QCString TranslatorSerbianCyrilic::trThisIsTheListOfAllMembers()
this is the first part of a sentence that is followed by a class name
virtual QCString TranslatorSerbianCyrilic::trIncludingInheritedMembers()
this is the remainder of the sentence after the class name
virtual QCString TranslatorSerbianCyrilic::trGeneratedAutomatically(const char *s)
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
virtual QCString TranslatorSerbianCyrilic::trEnumName()
put after an enum name in the list of all members
virtual QCString TranslatorSerbianCyrilic::trEnumValue()
put after an enum value in the list of all members
virtual QCString TranslatorSerbianCyrilic::trDefinedIn()
put after an undocumented member in the list of all members
virtual QCString TranslatorSerbianCyrilic::trModules()
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
virtual QCString TranslatorSerbianCyrilic::trClassHierarchy()
This is put above each page as a link to the class hierarchy
virtual QCString TranslatorSerbianCyrilic::trCompoundList()
This is put above each page as a link to the list of annotated classes
virtual QCString TranslatorSerbianCyrilic::trFileList()
This is put above each page as a link to the list of documented files
virtual QCString TranslatorSerbianCyrilic::trCompoundMembers()
This is put above each page as a link to all members of compounds.
virtual QCString TranslatorSerbianCyrilic::trFileMembers()
This is put above each page as a link to all members of files.
virtual QCString TranslatorSerbianCyrilic::trRelatedPages()
This is put above each page as a link to all related pages.
virtual QCString TranslatorSerbianCyrilic::trExamples()
This is put above each page as a link to all examples.
virtual QCString TranslatorSerbianCyrilic::trSearch()
This is put above each page as a link to the search engine.
virtual QCString TranslatorSerbianCyrilic::trClassHierarchyDescription()
This is an introduction to the class hierarchy.
virtual QCString TranslatorSerbianCyrilic::trFileListDescription(bool extractAll)
This is an introduction to the list with all files.
virtual QCString TranslatorSerbianCyrilic::trCompoundListDescription()
This is an introduction to the annotated compound list.
virtual QCString TranslatorSerbianCyrilic::trCompoundMembersDescription(bool extractAll)
This is an introduction to the page with all class members.
virtual QCString TranslatorSerbianCyrilic::trFileMembersDescription(bool extractAll)
This is an introduction to the page with all file members.
virtual QCString TranslatorSerbianCyrilic::trExamplesDescription()
This is an introduction to the page with the list of all examples
virtual QCString TranslatorSerbianCyrilic::trRelatedPagesDescription()
This is an introduction to the page with the list of related pages
virtual QCString TranslatorSerbianCyrilic::trModulesDescription()
This is an introduction to the page with the list of class/file groups
virtual QCString TranslatorSerbianCyrilic::trDocumentation()
This is used in HTML as the title of index.html.
virtual QCString TranslatorSerbianCyrilic::trModuleIndex()
This is used in LaTeX as the title of the chapter with the index of all groups.
virtual QCString TranslatorSerbianCyrilic::trHierarchicalIndex()
This is used in LaTeX as the title of the chapter with the class hierarchy.
virtual QCString TranslatorSerbianCyrilic::trCompoundIndex()
This is used in LaTeX as the title of the chapter with the annotated compound index.
virtual QCString TranslatorSerbianCyrilic::trFileIndex()
This is used in LaTeX as the title of the chapter with the list of all files.
virtual QCString TranslatorSerbianCyrilic::trModuleDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
virtual QCString TranslatorSerbianCyrilic::trClassDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
virtual QCString TranslatorSerbianCyrilic::trFileDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all files.
virtual QCString TranslatorSerbianCyrilic::trExampleDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
virtual QCString TranslatorSerbianCyrilic::trPageDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all related pages.
virtual QCString TranslatorSerbianCyrilic::trReferenceManual()
This is used in LaTeX as the title of the document
virtual QCString TranslatorSerbianCyrilic::trDefines()
This is used in the documentation of a file as a header before the list of defines
virtual QCString TranslatorSerbianCyrilic::trFuncProtos()
This is used in the documentation of a file as a header before the list of function prototypes
virtual QCString TranslatorSerbianCyrilic::trTypedefs()
This is used in the documentation of a file as a header before the list of typedefs
virtual QCString TranslatorSerbianCyrilic::trEnumerations()
This is used in the documentation of a file as a header before the list of enumerations
virtual QCString TranslatorSerbianCyrilic::trFunctions()
This is used in the documentation of a file as a header before the list of (global) functions
virtual QCString TranslatorSerbianCyrilic::trVariables()
This is used in the documentation of a file as a header before the list of (global) variables
virtual QCString TranslatorSerbianCyrilic::trEnumerationValues()
This is used in the documentation of a file as a header before the list of (global) variables
virtual QCString TranslatorSerbianCyrilic::trDefineDocumentation()
This is used in the documentation of a file before the list of documentation blocks for defines
virtual QCString TranslatorSerbianCyrilic::trFunctionPrototypeDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for function prototypes
virtual QCString TranslatorSerbianCyrilic::trTypedefDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
virtual QCString TranslatorSerbianCyrilic::trEnumerationTypeDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
virtual QCString TranslatorSerbianCyrilic::trFunctionDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
virtual QCString TranslatorSerbianCyrilic::trVariableDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
virtual QCString TranslatorSerbianCyrilic::trCompounds()
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
virtual QCString TranslatorSerbianCyrilic::trGeneratedAt(const char *date, const char *projName)
This is used in the standard footer of each page and indicates when the page was generated
virtual QCString TranslatorSerbianCyrilic::trWrittenBy()
This is part of the sentence used in the standard footer of each page.
virtual QCString TranslatorSerbianCyrilic::trClassDiagram(const char *clName)
this text is put before a class diagram
virtual QCString TranslatorSerbianCyrilic::trForInternalUseOnly()
this text is generated when the \internal command is used.
virtual QCString TranslatorSerbianCyrilic::trWarning()
this text is generated when the \warning command is used.
virtual QCString TranslatorSerbianCyrilic::trVersion()
this text is generated when the \version command is used.
virtual QCString TranslatorSerbianCyrilic::trDate()
this text is generated when the \date command is used.
virtual QCString TranslatorSerbianCyrilic::trReturns()
this text is generated when the \return command is used.
virtual QCString TranslatorSerbianCyrilic::trSeeAlso()
this text is generated when the \sa command is used.
virtual QCString TranslatorSerbianCyrilic::trParameters()
this text is generated when the \param command is used.
virtual QCString TranslatorSerbianCyrilic::trExceptions()
this text is generated when the \exception command is used.
virtual QCString TranslatorSerbianCyrilic::trGeneratedBy()
this text is used in the title page of a LaTeX document.
virtual QCString TranslatorSerbianCyrilic::trNamespaceList()
used as the title of page containing all the index of all namespaces.
virtual QCString TranslatorSerbianCyrilic::trNamespaceListDescription(bool extractAll)
used as an introduction to the namespace list
virtual QCString TranslatorSerbianCyrilic::trFriends()
used in the class documentation as a header before the list of all friends of a class
virtual QCString TranslatorSerbianCyrilic::trRelatedFunctionDocumentation()
used in the class documentation as a header before the list of all related classes
virtual QCString TranslatorSerbianCyrilic::trCompoundReference(const char *clName, ClassDef::CompoundType compType, bool isTemplate)
used as the title of the HTML page of a class/struct/union
virtual QCString TranslatorSerbianCyrilic::trFileReference(const char *fileName)
used as the title of the HTML page of a file
virtual QCString TranslatorSerbianCyrilic::trNamespaceReference(const char *namespaceName)
used as the title of the HTML page of a namespace
virtual QCString TranslatorSerbianCyrilic::trPublicMembers()
virtual QCString TranslatorSerbianCyrilic::trPublicSlots()
virtual QCString TranslatorSerbianCyrilic::trSignals()
virtual QCString TranslatorSerbianCyrilic::trStaticPublicMembers()
virtual QCString TranslatorSerbianCyrilic::trProtectedMembers()
virtual QCString TranslatorSerbianCyrilic::trProtectedSlots()
virtual QCString TranslatorSerbianCyrilic::trStaticProtectedMembers()
virtual QCString TranslatorSerbianCyrilic::trPrivateMembers()
virtual QCString TranslatorSerbianCyrilic::trPrivateSlots()
virtual QCString TranslatorSerbianCyrilic::trStaticPrivateMembers()
virtual QCString TranslatorSerbianCyrilic::trWriteList(int numEntries)
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Referenced by trImplementedFromList, trImplementedInList, trInheritedByList, trInheritsList, trReimplementedFromList, trReimplementedInList.
virtual QCString TranslatorSerbianCyrilic::trInheritsList(int numEntries)
used in class documentation to produce a list of base classes, if class diagrams are disabled.
References trWriteList.
virtual QCString TranslatorSerbianCyrilic::trInheritedByList(int numEntries)
used in class documentation to produce a list of super classes, if class diagrams are disabled.
References trWriteList.
virtual QCString TranslatorSerbianCyrilic::trReimplementedFromList(int numEntries)
used in member documentation blocks to produce a list of members that are hidden by this one.
References trWriteList.
virtual QCString TranslatorSerbianCyrilic::trReimplementedInList(int numEntries)
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
References trWriteList.
virtual QCString TranslatorSerbianCyrilic::trNamespaceMembers()
This is put above each page as a link to all members of namespaces.
virtual QCString TranslatorSerbianCyrilic::trNamespaceMemberDescription(bool extractAll)
This is an introduction to the page with all namespace members
virtual QCString TranslatorSerbianCyrilic::trNamespaceIndex()
This is used in LaTeX as the title of the chapter with the index of all namespaces.
virtual QCString TranslatorSerbianCyrilic::trNamespaceDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
virtual QCString TranslatorSerbianCyrilic::trNamespaces()
This is used in the documentation before the list of all namespaces in a file.
virtual QCString TranslatorSerbianCyrilic::trGeneratedFromFiles(ClassDef::CompoundType compType, bool single)
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
virtual QCString TranslatorSerbianCyrilic::trAlphabeticalList()
This is in the (quick) index as a link to the alphabetical compound list.
virtual QCString TranslatorSerbianCyrilic::trReturnValues()
This is used as the heading text for the retval command.
virtual QCString TranslatorSerbianCyrilic::trMainPage()
This is in the (quick) index as a link to the main page (index.html)
virtual QCString TranslatorSerbianCyrilic::trPageAbbreviation()
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
virtual QCString TranslatorSerbianCyrilic::trDefinedAtLineInSourceFile()
virtual QCString TranslatorSerbianCyrilic::trDefinedInSourceFile()
virtual QCString TranslatorSerbianCyrilic::trDeprecated()
virtual QCString TranslatorSerbianCyrilic::trCollaborationDiagram(const char *clName)
this text is put before a collaboration diagram
virtual QCString TranslatorSerbianCyrilic::trInclDepGraph(const char *fName)
this text is put before an include dependency graph
virtual QCString TranslatorSerbianCyrilic::trConstructorDocumentation()
header that is put before the list of constructor/destructors.
virtual QCString TranslatorSerbianCyrilic::trGotoSourceCode()
Used in the file documentation to point to the corresponding sources.
virtual QCString TranslatorSerbianCyrilic::trGotoDocumentation()
Used in the file sources to point to the corresponding documentation.
virtual QCString TranslatorSerbianCyrilic::trPrecondition()
Text for the \pre command
virtual QCString TranslatorSerbianCyrilic::trPostcondition()
Text for the \post command
virtual QCString TranslatorSerbianCyrilic::trInvariant()
Text for the \invariant command
virtual QCString TranslatorSerbianCyrilic::trInitialValue()
Text shown before a multi-line variable/enum initialization
virtual QCString TranslatorSerbianCyrilic::trCode()
Text used the source code in the file index
virtual QCString TranslatorSerbianCyrilic::trGraphicalHierarchy()
virtual QCString TranslatorSerbianCyrilic::trGotoGraphicalHierarchy()
virtual QCString TranslatorSerbianCyrilic::trGotoTextualHierarchy()
virtual QCString TranslatorSerbianCyrilic::trPageIndex()
virtual QCString TranslatorSerbianCyrilic::trNote()
virtual QCString TranslatorSerbianCyrilic::trPublicTypes()
virtual QCString TranslatorSerbianCyrilic::trPublicAttribs()
virtual QCString TranslatorSerbianCyrilic::trStaticPublicAttribs()
virtual QCString TranslatorSerbianCyrilic::trProtectedTypes()
virtual QCString TranslatorSerbianCyrilic::trProtectedAttribs()
virtual QCString TranslatorSerbianCyrilic::trStaticProtectedAttribs()
virtual QCString TranslatorSerbianCyrilic::trPrivateTypes()
virtual QCString TranslatorSerbianCyrilic::trPrivateAttribs()
virtual QCString TranslatorSerbianCyrilic::trStaticPrivateAttribs()
virtual QCString TranslatorSerbianCyrilic::trTodo()
Used as a marker that is put before a \todo item
virtual QCString TranslatorSerbianCyrilic::trTodoList()
Used as the header of the todo list
virtual QCString TranslatorSerbianCyrilic::trReferencedBy()
virtual QCString TranslatorSerbianCyrilic::trRemarks()
virtual QCString TranslatorSerbianCyrilic::trAttention()
virtual QCString TranslatorSerbianCyrilic::trInclByDepGraph()
virtual QCString TranslatorSerbianCyrilic::trSince()
virtual QCString TranslatorSerbianCyrilic::trLegendTitle()
title of the graph legend page
virtual QCString TranslatorSerbianCyrilic::trLegendDocs()
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
virtual QCString TranslatorSerbianCyrilic::trLegend()
text for the link to the legend page
virtual QCString TranslatorSerbianCyrilic::trTest()
Used as a marker that is put before a test item
virtual QCString TranslatorSerbianCyrilic::trTestList()
Used as the header of the test list
virtual QCString TranslatorSerbianCyrilic::trDCOPMethods()
Used as a section header for KDE-2 IDL methods
virtual QCString TranslatorSerbianCyrilic::trProperties()
Used as a section header for IDL properties
virtual QCString TranslatorSerbianCyrilic::trPropertyDocumentation()
Used as a section header for IDL property documentation
virtual QCString TranslatorSerbianCyrilic::trClasses()
Used for Java classes in the summary section of Java packages
virtual QCString TranslatorSerbianCyrilic::trPackage(const char *name)
Used as the title of a Java package
virtual QCString TranslatorSerbianCyrilic::trPackageList()
Title of the package index page
virtual QCString TranslatorSerbianCyrilic::trPackageListDescription()
The description of the package index page
virtual QCString TranslatorSerbianCyrilic::trPackages()
The link name in the Quick links header for each page
virtual QCString TranslatorSerbianCyrilic::trDefineValue()
Text shown before a multi-line define
virtual QCString TranslatorSerbianCyrilic::trBug()
Used as a marker that is put before a \bug item
virtual QCString TranslatorSerbianCyrilic::trBugList()
Used as the header of the bug list
virtual QCString TranslatorSerbianCyrilic::trRTFansicp()
Used as ansicpg for RTF file The following table shows the correlation of Charset name, Charset Value and <pre> Codepage number: Charset Name Charset Value(hex) Codepage number ------------------------------------------------------ DEFAULT_CHARSET 1 (x01) SYMBOL_CHARSET 2 (x02) OEM_CHARSET 255 (xFF) ANSI_CHARSET 0 (x00) 1252 RUSSIAN_CHARSET 204 (xCC) 1251 EE_CHARSET 238 (xEE) 1250 GREEK_CHARSET 161 (xA1) 1253 TURKISH_CHARSET 162 (xA2) 1254 BALTIC_CHARSET 186 (xBA) 1257 HEBREW_CHARSET 177 (xB1) 1255 ARABIC _CHARSET 178 (xB2) 1256 SHIFTJIS_CHARSET 128 (x80) 932 HANGEUL_CHARSET 129 (x81) 949 GB2313_CHARSET 134 (x86) 936 CHINESEBIG5_CHARSET 136 (x88) 950 </pre>
virtual QCString TranslatorSerbianCyrilic::trRTFCharSet()
Used as ansicpg for RTF fcharset trRTFansicp() for a table of possible values.
virtual QCString TranslatorSerbianCyrilic::trRTFGeneralIndex()
Used as header RTF general index
virtual QCString TranslatorSerbianCyrilic::trClass(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorSerbianCyrilic::trFile(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorSerbianCyrilic::trNamespace(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorSerbianCyrilic::trGroup(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorSerbianCyrilic::trPage(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorSerbianCyrilic::trMember(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorSerbianCyrilic::trGlobal(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorSerbianCyrilic::trAuthor(bool first_capital, bool singular)
This text is generated when the \author command is used and for the author section in man pages.
virtual QCString TranslatorSerbianCyrilic::trReferences()
This text is put before the list of members referenced by a member
virtual QCString TranslatorSerbianCyrilic::trImplementedFromList(int numEntries)
used in member documentation blocks to produce a list of members that are implemented by this one.
References trWriteList.
virtual QCString TranslatorSerbianCyrilic::trImplementedInList(int numEntries)
used in member documentation blocks to produce a list of all members that implement this abstract member.
References trWriteList.
virtual QCString TranslatorSerbianCyrilic::trRTFTableOfContents()
used in RTF documentation as a heading for the Table of Contents.
virtual QCString TranslatorSerbianCyrilic::trDeprecatedList()
Used as the header of the list of item that have been flagged deprecated
virtual QCString TranslatorSerbianCyrilic::trEvents()
Used as a header for declaration section of the events found in a C# program
virtual QCString TranslatorSerbianCyrilic::trEventDocumentation()
Header used for the documentation section of a class' events.
virtual QCString TranslatorSerbianCyrilic::trPackageTypes()
Used as a heading for a list of Java class types with package scope.
virtual QCString TranslatorSerbianCyrilic::trPackageMembers()
Used as a heading for a list of Java class functions with package scope.
virtual QCString TranslatorSerbianCyrilic::trStaticPackageMembers()
Used as a heading for a list of static Java class functions with package scope.
virtual QCString TranslatorSerbianCyrilic::trPackageAttribs()
Used as a heading for a list of Java class variables with package scope.
virtual QCString TranslatorSerbianCyrilic::trStaticPackageAttribs()
Used as a heading for a list of static Java class variables with package scope.
virtual QCString TranslatorSerbianCyrilic::trAll()
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
virtual QCString TranslatorSerbianCyrilic::trCallGraph()
Put in front of the call graph for a function.
virtual QCString TranslatorSerbianCyrilic::trSearchForIndex()
When the search engine is enabled this text is put in the header of each page before the field where one can enter the text to search for.
virtual QCString TranslatorSerbianCyrilic::trSearchResultsTitle()
This string is used as the title for the page listing the search results.
virtual QCString TranslatorSerbianCyrilic::trSearchResults(int numDocuments)
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
virtual QCString TranslatorSerbianCyrilic::trSearchMatches()
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
virtual QCString TranslatorSerbianCyrilic::trSourceFile(QCString &filename)
This is used in HTML as the title of page with source code for file filename
virtual QCString TranslatorSerbianCyrilic::trDirIndex()
This is used as the name of the chapter containing the directory hierarchy.
virtual QCString TranslatorSerbianCyrilic::trDirDocumentation()
This is used as the name of the chapter containing the documentation of the directories.
virtual QCString TranslatorSerbianCyrilic::trDirectories()
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
virtual QCString TranslatorSerbianCyrilic::trDirDescription()
This returns a sentences that introduces the directory hierarchy. and the fact that it is sorted alphabetically per level
virtual QCString TranslatorSerbianCyrilic::trDirReference(const char *dirName)
This returns the title of a directory page. The name of the directory is passed via dirName.
virtual QCString TranslatorSerbianCyrilic::trDir(bool first_capital, bool singular)
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
virtual QCString TranslatorSerbianCyrilic::trOverloadText()
This text is added to the documentation when the \overload command is used for a overloaded function.
virtual QCString TranslatorSerbianCyrilic::trCallerGraph()
This is used to introduce a caller (or called-by) graph
virtual QCString TranslatorSerbianCyrilic::trEnumerationValueDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
virtual QCString TranslatorSerbianCyrilic::trMemberFunctionDocumentationFortran()
header that is put before the list of member subprograms (Fortran).
virtual QCString TranslatorSerbianCyrilic::trCompoundListFortran()
This is put above each page as a link to the list of annotated data types (Fortran).
virtual QCString TranslatorSerbianCyrilic::trCompoundMembersFortran()
This is put above each page as a link to all members of compounds (Fortran).
virtual QCString TranslatorSerbianCyrilic::trCompoundListDescriptionFortran()
This is an introduction to the annotated compound list (Fortran).
virtual QCString TranslatorSerbianCyrilic::trCompoundMembersDescriptionFortran(bool extractAll)
This is an introduction to the page with all data types (Fortran).
virtual QCString TranslatorSerbianCyrilic::trCompoundIndexFortran()
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
virtual QCString TranslatorSerbianCyrilic::trTypeDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
virtual QCString TranslatorSerbianCyrilic::trSubprograms()
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
virtual QCString TranslatorSerbianCyrilic::trSubprogramDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
virtual QCString TranslatorSerbianCyrilic::trDataTypes()
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
virtual QCString TranslatorSerbianCyrilic::trModulesList()
used as the title of page containing all the index of all modules (Fortran).
virtual QCString TranslatorSerbianCyrilic::trModulesListDescription(bool extractAll)
used as an introduction to the modules list (Fortran)
virtual QCString TranslatorSerbianCyrilic::trCompoundReferenceFortran(const char *clName, ClassDef::CompoundType compType, bool isTemplate)
used as the title of the HTML page of a module/type (Fortran)
virtual QCString TranslatorSerbianCyrilic::trModuleReference(const char *namespaceName)
used as the title of the HTML page of a module (Fortran)
virtual QCString TranslatorSerbianCyrilic::trModulesMembers()
This is put above each page as a link to all members of modules. (Fortran)
virtual QCString TranslatorSerbianCyrilic::trModulesMemberDescription(bool extractAll)
This is an introduction to the page with all modules members (Fortran)
virtual QCString TranslatorSerbianCyrilic::trModulesIndex()
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
virtual QCString TranslatorSerbianCyrilic::trModule(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorSerbianCyrilic::trGeneratedFromFilesFortran(ClassDef::CompoundType compType, bool single)
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
virtual QCString TranslatorSerbianCyrilic::trType(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorSerbianCyrilic::trSubprogram(bool first_capital, bool singular)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorSerbianCyrilic::trTypeConstraints()
C# Type Constraint list