VhdlDocGen
VhdlClasses
VhdlKeyWords
VhdlDocGen::VhdlDocGen()
VhdlDocGen::~VhdlDocGen()
void VhdlDocGen::init()
QCString VhdlDocGen::convertFileNameToClassName(QCString name)
bool VhdlDocGen::isSubClass(ClassDef *cd, ClassDef *scd, bool followInstances, int level)
QCString VhdlDocGen::getIndexWord(const char *, int index)
bool VhdlDocGen::deleteCharRev(QCString &s, char c)
deletes a char backwards in a string
Referenced by parseFuncProto.
void VhdlDocGen::deleteAllChars(QCString &s, char c)
void VhdlDocGen::parseFuncProto(const char *text, QList< Argument > &, QCString &name, QCString &ret, bool doc=false)
parses a function proto text function string qlist stores the function types name points to the function name ret Stores the return type doc ???
References deleteCharRev.
void VhdlDocGen::computeVhdlComponentRelations()
QCString * VhdlDocGen::findKeyWord(const QCString &word)
returns the color of a keyword
Referenced by writeFormatString, writeFunctionProto, writeProcedureProto.
ClassDef * VhdlDocGen::getPackageName(const QCString &name)
MemberDef * VhdlDocGen::findMember(const QCString &className, const QCString &memName)
void VhdlDocGen::findAllPackages(const QCString &className, QDict< QCString > &)
finds all included packages of an Entity or Package
References ClassDef::getMemberList, Definition::name.
MemberDef * VhdlDocGen::findMemberDef(ClassDef *cd, const QCString &key, MemberListType type)
This function returns the entity|package in which the key (type) is found.
References ClassDef::getMemberList, Definition::name.
ClassDef * VhdlDocGen::getClass(const char *name)
MemberDef * VhdlDocGen::findFunction(const QList< Argument > &ql, const QCString &name, const QCString &package, bool type)
returns the function with the matching argument list is called in vhdlcode.l
References Argument::attrib, ClassDef::getMemberList, Definition::name, Argument::type.
QCString VhdlDocGen::getClassTitle(const ClassDef *)
returns the class title+ref
References ClassDef::displayName, ClassDef::protection.
void VhdlDocGen::writeInlineClassLink(const ClassDef *, OutputList &ol)
writes an inline link form entity|package to architecture|package body and vice verca
References ClassDef::className, OutputList::disable, OutputList::enable, ClassDef::protection.
bool VhdlDocGen::isConstraint(const MemberDef *mdef)
bool VhdlDocGen::isConfig(const MemberDef *mdef)
bool VhdlDocGen::isAlias(const MemberDef *mdef)
bool VhdlDocGen::isLibrary(const MemberDef *mdef)
bool VhdlDocGen::isGeneric(const MemberDef *mdef)
bool VhdlDocGen::isPort(const MemberDef *mdef)
bool VhdlDocGen::isComponent(const MemberDef *mdef)
bool VhdlDocGen::isPackage(const MemberDef *mdef)
bool VhdlDocGen::isEntity(const MemberDef *mdef)
bool VhdlDocGen::isConstant(const MemberDef *mdef)
bool VhdlDocGen::isVType(const MemberDef *mdef)
bool VhdlDocGen::isSubType(const MemberDef *mdef)
bool VhdlDocGen::isVhdlFunction(const MemberDef *mdef)
bool VhdlDocGen::isProcess(const MemberDef *mdef)
bool VhdlDocGen::isSignal(const MemberDef *mdef)
bool VhdlDocGen::isAttribute(const MemberDef *mdef)
bool VhdlDocGen::isSignals(const MemberDef *mdef)
bool VhdlDocGen::isProcedure(const MemberDef *mdef)
bool VhdlDocGen::isRecord(const MemberDef *mdef)
bool VhdlDocGen::isArchitecture(const MemberDef *mdef)
bool VhdlDocGen::isUnit(const MemberDef *mdef)
bool VhdlDocGen::isPackageBody(const MemberDef *mdef)
bool VhdlDocGen::isVariable(const MemberDef *mdef)
bool VhdlDocGen::isFile(const MemberDef *mdef)
bool VhdlDocGen::isGroup(const MemberDef *mdef)
bool VhdlDocGen::isCompInst(const MemberDef *mdef)
bool VhdlDocGen::isMisc(const MemberDef *mdef)
QCString VhdlDocGen::trTypeString(uint64 type)
QCString VhdlDocGen::trVhdlType(uint64 type, bool sing=true)
QCString VhdlDocGen::trDesignUnitHierarchy()
QCString VhdlDocGen::trDesignUnitList()
QCString VhdlDocGen::trDesignUnitMembers()
QCString VhdlDocGen::trDesignUnitListDescription()
QCString VhdlDocGen::trDesignUnits()
QCString VhdlDocGen::trDesignUnitIndex()
QCString VhdlDocGen::trFunctionAndProc()
void VhdlDocGen::prepareComment(QCString &)
strips the "&ndash;" prefixes of vhdl comments
void VhdlDocGen::formatString(const QCString &, OutputList &ol, const MemberDef *)
inserts white spaces for better readings and writes a colored string to the output
References writeFormatString.
Referenced by writeFunctionProto, writeProcedureProto, writeVHDLDeclaration.
void VhdlDocGen::writeFormatString(const QCString &, OutputList &ol, const MemberDef *)
writes a colored and formatted string
References OutputList::docify, OutputList::endBold, findKeyWord, isNumber, OutputList::startBold.
Referenced by formatString, writeFuncProcDocu, writeProcessProto.
void VhdlDocGen::writeFunctionProto(OutputList &ol, const ArgumentList *al, const MemberDef *)
writes a function prototype to the output
References Argument::attrib, Argument::defval, OutputList::docify, OutputList::endBold, findKeyWord, formatString, Argument::name, OutputList::startBold, Argument::type.
Referenced by writeVHDLDeclaration.
void VhdlDocGen::writeProcessProto(OutputList &ol, const ArgumentList *al, const MemberDef *)
writes a process prototype to the output
References OutputList::docify, OutputList::endBold, Argument::name, OutputList::startBold, writeFormatString.
Referenced by writeVHDLDeclaration.
void VhdlDocGen::writeProcedureProto(OutputList &ol, const ArgumentList *al, const MemberDef *)
writes a procedure prototype to the output
References Argument::attrib, Argument::defval, OutputList::docify, OutputList::endBold, findKeyWord, formatString, Argument::name, OutputList::startBold, Argument::type, OutputList::writeChar.
Referenced by writeVHDLDeclaration.
bool VhdlDocGen::writeFuncProcDocu(const MemberDef *mdef, OutputList &ol, const ArgumentList *al, bool type=false)
writes a function|procedure documentation to the output
References Argument::attrib, Argument::defval, OutputList::disable, OutputList::docify, OutputList::enable, OutputList::enableAll, OutputList::endEmphasis, Argument::name, OutputList::startEmphasis, Argument::type, writeFormatString.
static void VhdlDocGen::writeRecordProto(const MemberDef *mdef, OutputList &ol, const ArgumentList *al)
bool VhdlDocGen::writeVHDLTypeDocumentation(const MemberDef *mdef, const Definition *d, OutputList &ol)
void VhdlDocGen::writeVhdlDeclarations(MemberList *, OutputList &, GroupDef *, ClassDef *, FileDef *, NamespaceDef *)
void VhdlDocGen::writeVHDLDeclaration(MemberDef *mdef, OutputList &ol, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd, bool inGroup)
References MemberDef::anchor, Definition::briefDescription, Definition::briefFile, Definition::briefLine, OutputList::disable, OutputList::disableAllBut, OutputList::docify, OutputList::enable, OutputList::endBold, OutputList::endEmphasis, formatString, MemberDef::getClassDefOfAnonymousType, MemberDef::getOutputFileBase, ClassDef::getOutputFileBase, Definition::getOutputFileBase, MemberDef::getReference, ClassDef::getReference, OutputList::isEnabled, Definition::localName, Definition::name, OutputList::popGeneratorState, ClassDef::protection, OutputList::pushGeneratorState, MemberDef::qualifiedName, Definition::setName, OutputList::startBold, OutputList::startEmphasis, Definition::writeDocAnchorsToTagFile, writeFunctionProto, OutputList::writeObjectLink, writeProcedureProto, writeProcessProto.
void VhdlDocGen::writePlainVHDLDeclarations(MemberList *ml, OutputList &ol, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd, int specifier)
void VhdlDocGen::writeVHDLDeclarations(MemberList *ml, OutputList &ol, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd, const char *title, const char *subtitle, bool showEnumValues, int type)
bool VhdlDocGen::writeClassType(ClassDef *&, OutputList &ol, QCString &cname)
QCString VhdlDocGen::convertArgumentListToString(const ArgumentList *al, bool f)
QCString VhdlDocGen::getProcessNumber()
returns the next number of an anonymous process
QCString VhdlDocGen::getRecordNumber()
returns the next number of a record|unit member
QCString VhdlDocGen::getClassName(const ClassDef *)
bool VhdlDocGen::isNumber(const QCString &s)
returns TRUE if this string is a number
Referenced by writeFormatString.
QCString VhdlDocGen::getProtectionName(int prot)
void VhdlDocGen::parseUCF(const char *input, Entry *entity, QCString f, bool vendor)
bool VhdlDocGen::findConstraintFile(LayoutNavEntry *lne)
ClassDef * VhdlDocGen::findArchitecture(const ClassDef *cd)
static ClassDef* VhdlDocGen::findArchitecture(QCString identifier, QCString entity_name)
void VhdlDocGen::writeSource(MemberDef *mdef, OutputList &ol, QCString &cname)
static void VhdlDocGen::writeAlphbeticalClass(OutputList &ol, const ClassDef *cd, const QCString &)
QCString VhdlDocGen::parseForConfig(QCString &entity, QCString &arch)
QCString VhdlDocGen::parseForBinding(QCString &entity, QCString &arch)
void VhdlDocGen::addBaseClass(ClassDef *cd, ClassDef *ent)
ClassDef * VhdlDocGen::findVhdlClass(const char *className)
static void VhdlDocGen::writeOverview(OutputList &ol)
void VhdlDocGen::writeOverview()
void VhdlDocGen::createFlowChart(const MemberDef *)
void VhdlDocGen::setFlowMember(const MemberDef *flowMember)
const MemberDef * VhdlDocGen::getFlowMember()
static bool VhdlDocGen::isVhdlClass(const Entry *cu)
void VhdlDocGen::findAllArchitectures(QList< QCString > &ql, const ClassDef *cd)
static bool VhdlDocGen::compareArgList(ArgumentList *, ArgumentList *)
void VhdlDocGen::writeVhdlLink(const ClassDef *cdd, OutputList &ol, QCString &type, QCString &name, QCString &beh)
void VhdlDocGen::writeStringLink(const MemberDef *mdef, QCString mem, OutputList &ol)
writes a link if the string is linkable else a formatted string
void VhdlDocGen::writeRecUnitDocu(const MemberDef *md, OutputList &ol, QCString largs)
void VhdlDocGen::writeRecorUnit(QCString &largs, OutputList &ol, const MemberDef *mdef)