SDict
SList<T>* SDict< T >::m_list
QDict<T>* SDict< T >::m_dict
int SDict< T >::m_sizeIndex
friend class Iterator
friend class IteratorDict
SDict< T >::SDict(int size, bool caseSensitive=TRUE)
Create an ordered dictionary. size The size of the dictionary. Should be a prime number for best distribution of elements. caseSensitive indicated whether the keys should be sorted in a case sensitive way.
virtual SDict< T >::~SDict()
Destroys the dictionary
void SDict< T >::append(const char *key, const T *d)
Appends an element to the dictionary. The element is owned by the dictionary. key The unique key to use to quicky find the item later on. d The compound to add. find()
Referenced by Definition::addSectionsToDefinition, FileDef::insertClass, FileDef::insertNamespace, ClassDef::mergeCategory, ClassDef::mergeMembers.
void SDict< T >::prepend(const char *key, const T *d)
Prepends an element to the dictionary. The element is owned by the dictionary. key The unique key to use to quicky find the item later on. d The compound to add. find()
bool SDict< T >::remove(const char *key)
Remove an item from the dictionary
T* SDict< T >::take(const char *key)
Take an item out of the dictionary without deleting it
void SDict< T >::sort()
Sorts the members of the dictionary. First appending a number of members and then sorting them is faster (O(NlogN) than using inSort() for each member (O(N^2)).
void SDict< T >::inSort(const char *key, const T *d)
Inserts a compound into the dictionary in a sorted way. key The unique key to use to quicky find the item later on. d The compound to add. find()
Referenced by FileDef::insertClass, FileDef::insertNamespace.
void SDict< T >::insertAt(int i, const char *key, const T *d)
void SDict< T >::setAutoDelete(bool val)
Indicates whether or not the dictionary owns its elements
T* SDict< T >::find(const char *key)
Looks up a compound given its key. key The key to identify this element. The requested compound or zero if it cannot be found. append()
Referenced by Definition::addSectionsToDefinition, getClass, getDefs, FileDef::insertNamespace, ClassDef::mergeCategory, ClassDef::mergeMembers, resolveRef.
T* SDict< T >::find(const QCString &key)
T* SDict< T >::find(const QString &key)
int SDict< T >::findAt(const QCString &key)
T* SDict< T >::operator[](const char *key) const
Equavalent to find().
T* SDict< T >::at(uint i)
Returns the item at position i in the sorted dictionary
virtual int SDict< T >::compareItems(QCollection::Item item1, QCollection::Item item2)
Function that is used to compare two items when sorting. Overload this to properly sort items. inSort()
void SDict< T >::clear()
Clears the dictionary. Will delete items if setAutoDelete() was set to TRUE. setAutoDelete
int SDict< T >::count() const
Returns the number of items stored in the dictionary