TranslatorChinesetraditional
virtual QCString TranslatorChinesetraditional::idLanguage()
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
virtual QCString TranslatorChinesetraditional::latexLanguageSupportCommand()
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example "\\usepackage[german]{babel}\n" or "\\usepackage{polski}\n" "\\usepackage[latin2]{inputenc}\n" "\\usepackage[T1]{fontenc}\n" The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
virtual QCString TranslatorChinesetraditional::idLanguageCharset()
return the language charset. This will be used for the HTML output
virtual QCString TranslatorChinesetraditional::trRelatedFunctions()
used in the compound documentation before a list of related functions.
virtual QCString TranslatorChinesetraditional::trRelatedSubscript()
subscript for the related functions.
virtual QCString TranslatorChinesetraditional::trDetailedDescription()
header that is put before the detailed description of files, classes and namespaces.
virtual QCString TranslatorChinesetraditional::trMemberTypedefDocumentation()
header that is put before the list of typedefs.
virtual QCString TranslatorChinesetraditional::trMemberEnumerationDocumentation()
header that is put before the list of enumerations.
virtual QCString TranslatorChinesetraditional::trMemberFunctionDocumentation()
header that is put before the list of member functions.
virtual QCString TranslatorChinesetraditional::trMemberDataDocumentation()
header that is put before the list of member attributes.
virtual QCString TranslatorChinesetraditional::trMore()
this is the text of a link put after brief descriptions.
virtual QCString TranslatorChinesetraditional::trListOfAllMembers()
put in the class documentation
virtual QCString TranslatorChinesetraditional::trMemberList()
used as the title of the "list of all members" page of a class
virtual QCString TranslatorChinesetraditional::trThisIsTheListOfAllMembers()
this is the first part of a sentence that is followed by a class name
virtual QCString TranslatorChinesetraditional::trIncludingInheritedMembers()
this is the remainder of the sentence after the class name
virtual QCString TranslatorChinesetraditional::trGeneratedAutomatically(const char *s)
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
virtual QCString TranslatorChinesetraditional::trEnumName()
put after an enum name in the list of all members
virtual QCString TranslatorChinesetraditional::trEnumValue()
put after an enum value in the list of all members
virtual QCString TranslatorChinesetraditional::trDefinedIn()
put after an undocumented member in the list of all members
virtual QCString TranslatorChinesetraditional::trModules()
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
virtual QCString TranslatorChinesetraditional::trClassHierarchy()
This is put above each page as a link to the class hierarchy
virtual QCString TranslatorChinesetraditional::trCompoundList()
This is put above each page as a link to the list of annotated classes
virtual QCString TranslatorChinesetraditional::trFileList()
This is put above each page as a link to the list of documented files
virtual QCString TranslatorChinesetraditional::trCompoundMembers()
This is put above each page as a link to all members of compounds.
virtual QCString TranslatorChinesetraditional::trFileMembers()
This is put above each page as a link to all members of files.
virtual QCString TranslatorChinesetraditional::trRelatedPages()
This is put above each page as a link to all related pages.
virtual QCString TranslatorChinesetraditional::trExamples()
This is put above each page as a link to all examples.
virtual QCString TranslatorChinesetraditional::trSearch()
This is put above each page as a link to the search engine.
virtual QCString TranslatorChinesetraditional::trClassHierarchyDescription()
This is an introduction to the class hierarchy.
virtual QCString TranslatorChinesetraditional::trFileListDescription(bool extractAll)
This is an introduction to the list with all files.
virtual QCString TranslatorChinesetraditional::trCompoundListDescription()
This is an introduction to the annotated compound list.
virtual QCString TranslatorChinesetraditional::trCompoundMembersDescription(bool extractAll)
This is an introduction to the page with all class members.
virtual QCString TranslatorChinesetraditional::trFileMembersDescription(bool extractAll)
This is an introduction to the page with all file members.
virtual QCString TranslatorChinesetraditional::trExamplesDescription()
This is an introduction to the page with the list of all examples
virtual QCString TranslatorChinesetraditional::trRelatedPagesDescription()
This is an introduction to the page with the list of related pages
virtual QCString TranslatorChinesetraditional::trModulesDescription()
This is an introduction to the page with the list of class/file groups
virtual QCString TranslatorChinesetraditional::trDocumentation()
This is used in HTML as the title of index.html.
virtual QCString TranslatorChinesetraditional::trModuleIndex()
This is used in LaTeX as the title of the chapter with the index of all groups.
virtual QCString TranslatorChinesetraditional::trHierarchicalIndex()
This is used in LaTeX as the title of the chapter with the class hierarchy.
virtual QCString TranslatorChinesetraditional::trCompoundIndex()
This is used in LaTeX as the title of the chapter with the annotated compound index.
virtual QCString TranslatorChinesetraditional::trFileIndex()
This is used in LaTeX as the title of the chapter with the list of all files.
virtual QCString TranslatorChinesetraditional::trModuleDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
virtual QCString TranslatorChinesetraditional::trClassDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
virtual QCString TranslatorChinesetraditional::trFileDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all files.
virtual QCString TranslatorChinesetraditional::trExampleDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
virtual QCString TranslatorChinesetraditional::trPageDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all related pages.
virtual QCString TranslatorChinesetraditional::trReferenceManual()
This is used in LaTeX as the title of the document
virtual QCString TranslatorChinesetraditional::trDefines()
This is used in the documentation of a file as a header before the list of defines
virtual QCString TranslatorChinesetraditional::trFuncProtos()
This is used in the documentation of a file as a header before the list of function prototypes
virtual QCString TranslatorChinesetraditional::trTypedefs()
This is used in the documentation of a file as a header before the list of typedefs
virtual QCString TranslatorChinesetraditional::trEnumerations()
This is used in the documentation of a file as a header before the list of enumerations
virtual QCString TranslatorChinesetraditional::trFunctions()
This is used in the documentation of a file as a header before the list of (global) functions
virtual QCString TranslatorChinesetraditional::trVariables()
This is used in the documentation of a file as a header before the list of (global) variables
virtual QCString TranslatorChinesetraditional::trEnumerationValues()
This is used in the documentation of a file as a header before the list of (global) variables
virtual QCString TranslatorChinesetraditional::trDefineDocumentation()
This is used in the documentation of a file before the list of documentation blocks for defines
virtual QCString TranslatorChinesetraditional::trFunctionPrototypeDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for function prototypes
virtual QCString TranslatorChinesetraditional::trTypedefDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
virtual QCString TranslatorChinesetraditional::trEnumerationTypeDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
virtual QCString TranslatorChinesetraditional::trEnumerationValueDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
virtual QCString TranslatorChinesetraditional::trFunctionDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
virtual QCString TranslatorChinesetraditional::trVariableDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
virtual QCString TranslatorChinesetraditional::trCompounds()
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
virtual QCString TranslatorChinesetraditional::trGeneratedAt(const char *date, const char *projName)
This is used in the standard footer of each page and indicates when the page was generated
virtual QCString TranslatorChinesetraditional::trWrittenBy()
This is part of the sentence used in the standard footer of each page.
virtual QCString TranslatorChinesetraditional::trClassDiagram(const char *clName)
this text is put before a class diagram
virtual QCString TranslatorChinesetraditional::trForInternalUseOnly()
this text is generated when the \internal command is used.
virtual QCString TranslatorChinesetraditional::trWarning()
this text is generated when the \warning command is used.
virtual QCString TranslatorChinesetraditional::trVersion()
this text is generated when the \version command is used.
virtual QCString TranslatorChinesetraditional::trDate()
this text is generated when the \date command is used.
virtual QCString TranslatorChinesetraditional::trReturns()
this text is generated when the \return command is used.
virtual QCString TranslatorChinesetraditional::trSeeAlso()
this text is generated when the \sa command is used.
virtual QCString TranslatorChinesetraditional::trParameters()
this text is generated when the \param command is used.
virtual QCString TranslatorChinesetraditional::trExceptions()
this text is generated when the \exception command is used.
virtual QCString TranslatorChinesetraditional::trGeneratedBy()
this text is used in the title page of a LaTeX document.
virtual QCString TranslatorChinesetraditional::trNamespaceList()
used as the title of page containing all the index of all namespaces.
virtual QCString TranslatorChinesetraditional::trNamespaceListDescription(bool extractAll)
used as an introduction to the namespace list
virtual QCString TranslatorChinesetraditional::trFriends()
used in the class documentation as a header before the list of all friends of a class
virtual QCString TranslatorChinesetraditional::trRelatedFunctionDocumentation()
used in the class documentation as a header before the list of all related classes
virtual QCString TranslatorChinesetraditional::trCompoundReference(const char *clName, ClassDef::CompoundType compType, bool isTemplate)
used as the title of the HTML page of a class/struct/union
virtual QCString TranslatorChinesetraditional::trFileReference(const char *fileName)
used as the title of the HTML page of a file
virtual QCString TranslatorChinesetraditional::trNamespaceReference(const char *namespaceName)
used as the title of the HTML page of a namespace
virtual QCString TranslatorChinesetraditional::trPublicMembers()
virtual QCString TranslatorChinesetraditional::trPublicSlots()
virtual QCString TranslatorChinesetraditional::trSignals()
virtual QCString TranslatorChinesetraditional::trStaticPublicMembers()
virtual QCString TranslatorChinesetraditional::trProtectedMembers()
virtual QCString TranslatorChinesetraditional::trProtectedSlots()
virtual QCString TranslatorChinesetraditional::trStaticProtectedMembers()
virtual QCString TranslatorChinesetraditional::trPrivateMembers()
virtual QCString TranslatorChinesetraditional::trPrivateSlots()
virtual QCString TranslatorChinesetraditional::trStaticPrivateMembers()
virtual QCString TranslatorChinesetraditional::trWriteList(int numEntries)
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Referenced by trImplementedFromList, trImplementedInList, trInheritedByList, trInheritsList, trReimplementedFromList, trReimplementedInList.
virtual QCString TranslatorChinesetraditional::trInheritsList(int numEntries)
used in class documentation to produce a list of base classes, if class diagrams are disabled.
References trWriteList.
virtual QCString TranslatorChinesetraditional::trInheritedByList(int numEntries)
used in class documentation to produce a list of super classes, if class diagrams are disabled.
References trWriteList.
virtual QCString TranslatorChinesetraditional::trReimplementedFromList(int numEntries)
used in member documentation blocks to produce a list of members that are hidden by this one.
References trWriteList.
virtual QCString TranslatorChinesetraditional::trReimplementedInList(int numEntries)
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
References trWriteList.
virtual QCString TranslatorChinesetraditional::trNamespaceMembers()
This is put above each page as a link to all members of namespaces.
virtual QCString TranslatorChinesetraditional::trNamespaceMemberDescription(bool extractAll)
This is an introduction to the page with all namespace members
virtual QCString TranslatorChinesetraditional::trNamespaceIndex()
This is used in LaTeX as the title of the chapter with the index of all namespaces.
virtual QCString TranslatorChinesetraditional::trNamespaceDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
virtual QCString TranslatorChinesetraditional::trNamespaces()
This is used in the documentation before the list of all namespaces in a file.
virtual QCString TranslatorChinesetraditional::trGeneratedFromFiles(ClassDef::CompoundType compType, bool single)
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
virtual QCString TranslatorChinesetraditional::trAlphabeticalList()
This is in the (quick) index as a link to the alphabetical compound list.
virtual QCString TranslatorChinesetraditional::trReturnValues()
This is used as the heading text for the retval command.
virtual QCString TranslatorChinesetraditional::trMainPage()
This is in the (quick) index as a link to the main page (index.html)
virtual QCString TranslatorChinesetraditional::trPageAbbreviation()
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
virtual QCString TranslatorChinesetraditional::trDefinedAtLineInSourceFile()
virtual QCString TranslatorChinesetraditional::trDefinedInSourceFile()
virtual QCString TranslatorChinesetraditional::trDeprecated()
virtual QCString TranslatorChinesetraditional::trCollaborationDiagram(const char *clName)
this text is put before a collaboration diagram
virtual QCString TranslatorChinesetraditional::trInclDepGraph(const char *fName)
this text is put before an include dependency graph
virtual QCString TranslatorChinesetraditional::trConstructorDocumentation()
header that is put before the list of constructor/destructors.
virtual QCString TranslatorChinesetraditional::trGotoSourceCode()
Used in the file documentation to point to the corresponding sources.
virtual QCString TranslatorChinesetraditional::trGotoDocumentation()
Used in the file sources to point to the corresponding documentation.
virtual QCString TranslatorChinesetraditional::trPrecondition()
Text for the \pre command
virtual QCString TranslatorChinesetraditional::trPostcondition()
Text for the \post command
virtual QCString TranslatorChinesetraditional::trInvariant()
Text for the \invariant command
virtual QCString TranslatorChinesetraditional::trInitialValue()
Text shown before a multi-line variable/enum initialization
virtual QCString TranslatorChinesetraditional::trCode()
Text used the source code in the file index
virtual QCString TranslatorChinesetraditional::trGraphicalHierarchy()
virtual QCString TranslatorChinesetraditional::trGotoGraphicalHierarchy()
virtual QCString TranslatorChinesetraditional::trGotoTextualHierarchy()
virtual QCString TranslatorChinesetraditional::trPageIndex()
virtual QCString TranslatorChinesetraditional::trNote()
virtual QCString TranslatorChinesetraditional::trPublicTypes()
virtual QCString TranslatorChinesetraditional::trPublicAttribs()
virtual QCString TranslatorChinesetraditional::trStaticPublicAttribs()
virtual QCString TranslatorChinesetraditional::trProtectedTypes()
virtual QCString TranslatorChinesetraditional::trProtectedAttribs()
virtual QCString TranslatorChinesetraditional::trStaticProtectedAttribs()
virtual QCString TranslatorChinesetraditional::trPrivateTypes()
virtual QCString TranslatorChinesetraditional::trPrivateAttribs()
virtual QCString TranslatorChinesetraditional::trStaticPrivateAttribs()
virtual QCString TranslatorChinesetraditional::trTodo()
Used as a marker that is put before a \todo item
virtual QCString TranslatorChinesetraditional::trTodoList()
Used as the header of the todo list
virtual QCString TranslatorChinesetraditional::trReferencedBy()
virtual QCString TranslatorChinesetraditional::trRemarks()
virtual QCString TranslatorChinesetraditional::trAttention()
virtual QCString TranslatorChinesetraditional::trInclByDepGraph()
virtual QCString TranslatorChinesetraditional::trSince()
virtual QCString TranslatorChinesetraditional::trLegendTitle()
title of the graph legend page
virtual QCString TranslatorChinesetraditional::trLegendDocs()
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
virtual QCString TranslatorChinesetraditional::trLegend()
text for the link to the legend page
virtual QCString TranslatorChinesetraditional::trTest()
Used as a marker that is put before a test item
virtual QCString TranslatorChinesetraditional::trTestList()
Used as the header of the test list
virtual QCString TranslatorChinesetraditional::trDCOPMethods()
Used as a section header for KDE-2 IDL methods
virtual QCString TranslatorChinesetraditional::trProperties()
Used as a section header for IDL properties
virtual QCString TranslatorChinesetraditional::trPropertyDocumentation()
Used as a section header for IDL property documentation
virtual QCString TranslatorChinesetraditional::trClasses()
Used for Java classes in the summary section of Java packages
virtual QCString TranslatorChinesetraditional::trPackage(const char *name)
Used as the title of a Java package
virtual QCString TranslatorChinesetraditional::trPackageList()
Title of the package index page
virtual QCString TranslatorChinesetraditional::trPackageListDescription()
The description of the package index page
virtual QCString TranslatorChinesetraditional::trPackages()
The link name in the Quick links header for each page
virtual QCString TranslatorChinesetraditional::trDefineValue()
Text shown before a multi-line define
virtual QCString TranslatorChinesetraditional::trBug()
Used as a marker that is put before a \bug item
virtual QCString TranslatorChinesetraditional::trBugList()
Used as the header of the bug list
virtual QCString TranslatorChinesetraditional::trRTFansicp()
Used as ansicpg for RTF file The following table shows the correlation of Charset name, Charset Value and <pre> Codepage number: Charset Name Charset Value(hex) Codepage number ------------------------------------------------------ DEFAULT_CHARSET 1 (x01) SYMBOL_CHARSET 2 (x02) OEM_CHARSET 255 (xFF) ANSI_CHARSET 0 (x00) 1252 RUSSIAN_CHARSET 204 (xCC) 1251 EE_CHARSET 238 (xEE) 1250 GREEK_CHARSET 161 (xA1) 1253 TURKISH_CHARSET 162 (xA2) 1254 BALTIC_CHARSET 186 (xBA) 1257 HEBREW_CHARSET 177 (xB1) 1255 ARABIC _CHARSET 178 (xB2) 1256 SHIFTJIS_CHARSET 128 (x80) 932 HANGEUL_CHARSET 129 (x81) 949 GB2313_CHARSET 134 (x86) 936 CHINESEBIG5_CHARSET 136 (x88) 950 </pre>
virtual QCString TranslatorChinesetraditional::trRTFCharSet()
Used as ansicpg for RTF fcharset trRTFansicp() for a table of possible values.
virtual QCString TranslatorChinesetraditional::trRTFGeneralIndex()
Used as header RTF general index
virtual QCString TranslatorChinesetraditional::trClass(bool, bool)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorChinesetraditional::trFile(bool, bool)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorChinesetraditional::trNamespace(bool, bool)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorChinesetraditional::trGroup(bool, bool)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorChinesetraditional::trPage(bool, bool)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorChinesetraditional::trMember(bool, bool)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorChinesetraditional::trGlobal(bool, bool)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorChinesetraditional::trAuthor(bool, bool)
This text is generated when the \author command is used and for the author section in man pages.
virtual QCString TranslatorChinesetraditional::trReferences()
This text is put before the list of members referenced by a member
virtual QCString TranslatorChinesetraditional::trImplementedFromList(int numEntries)
used in member documentation blocks to produce a list of members that are implemented by this one.
References trWriteList.
virtual QCString TranslatorChinesetraditional::trImplementedInList(int numEntries)
used in member documentation blocks to produce a list of all members that implement this abstract member.
References trWriteList.
virtual QCString TranslatorChinesetraditional::trRTFTableOfContents()
used in RTF documentation as a heading for the Table of Contents.
virtual QCString TranslatorChinesetraditional::trDeprecatedList()
Used as the header of the list of item that have been flagged deprecated
virtual QCString TranslatorChinesetraditional::trEvents()
Used as a header for declaration section of the events found in a C# program
virtual QCString TranslatorChinesetraditional::trEventDocumentation()
Header used for the documentation section of a class' events.
virtual QCString TranslatorChinesetraditional::trPackageTypes()
Used as a heading for a list of Java class types with package scope.
virtual QCString TranslatorChinesetraditional::trPackageMembers()
Used as a heading for a list of Java class functions with package scope.
virtual QCString TranslatorChinesetraditional::trStaticPackageMembers()
Used as a heading for a list of static Java class functions with package scope.
virtual QCString TranslatorChinesetraditional::trPackageAttribs()
Used as a heading for a list of Java class variables with package scope.
virtual QCString TranslatorChinesetraditional::trStaticPackageAttribs()
Used as a heading for a list of static Java class variables with package scope.
virtual QCString TranslatorChinesetraditional::trAll()
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
virtual QCString TranslatorChinesetraditional::trCallGraph()
Put in front of the call graph for a function.
virtual QCString TranslatorChinesetraditional::trSearchForIndex()
When the search engine is enabled this text is put in the header of each page before the field where one can enter the text to search for.
virtual QCString TranslatorChinesetraditional::trSearchResultsTitle()
This string is used as the title for the page listing the search results.
virtual QCString TranslatorChinesetraditional::trSearchResults(int numDocuments)
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
virtual QCString TranslatorChinesetraditional::trSearchMatches()
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
virtual QCString TranslatorChinesetraditional::trSourceFile(QCString &filename)
This is used in HTML as the title of page with source code for file filename
virtual QCString TranslatorChinesetraditional::trDirIndex()
This is used as the name of the chapter containing the directory hierarchy.
virtual QCString TranslatorChinesetraditional::trDirDocumentation()
This is used as the name of the chapter containing the documentation of the directories.
virtual QCString TranslatorChinesetraditional::trDirectories()
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
virtual QCString TranslatorChinesetraditional::trDirDescription()
This returns a sentences that introduces the directory hierarchy. and the fact that it is sorted alphabetically per level
virtual QCString TranslatorChinesetraditional::trDirReference(const char *dirName)
This returns the title of a directory page. The name of the directory is passed via dirName.
virtual QCString TranslatorChinesetraditional::trDir(bool, bool)
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
virtual QCString TranslatorChinesetraditional::trOverloadText()
This text is added to the documentation when the \overload command is used for a overloaded function.
virtual QCString TranslatorChinesetraditional::trCallerGraph()
This is used to introduce a caller (or called-by) graph
virtual QCString TranslatorChinesetraditional::trMemberFunctionDocumentationFortran()
header that is put before the list of member subprograms (Fortran).
virtual QCString TranslatorChinesetraditional::trCompoundListFortran()
This is put above each page as a link to the list of annotated data types (Fortran).
virtual QCString TranslatorChinesetraditional::trCompoundMembersFortran()
This is put above each page as a link to all members of compounds (Fortran).
virtual QCString TranslatorChinesetraditional::trCompoundListDescriptionFortran()
This is an introduction to the annotated compound list (Fortran).
virtual QCString TranslatorChinesetraditional::trCompoundMembersDescriptionFortran(bool extractAll)
This is an introduction to the page with all data types (Fortran).
virtual QCString TranslatorChinesetraditional::trCompoundIndexFortran()
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
virtual QCString TranslatorChinesetraditional::trTypeDocumentation()
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
virtual QCString TranslatorChinesetraditional::trSubprograms()
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
virtual QCString TranslatorChinesetraditional::trSubprogramDocumentation()
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
virtual QCString TranslatorChinesetraditional::trDataTypes()
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
virtual QCString TranslatorChinesetraditional::trModulesList()
used as the title of page containing all the index of all modules (Fortran).
virtual QCString TranslatorChinesetraditional::trModulesListDescription(bool extractAll)
used as an introduction to the modules list (Fortran)
virtual QCString TranslatorChinesetraditional::trCompoundReferenceFortran(const char *clName, ClassDef::CompoundType compType, bool isTemplate)
used as the title of the HTML page of a module/type (Fortran)
virtual QCString TranslatorChinesetraditional::trModuleReference(const char *namespaceName)
used as the title of the HTML page of a module (Fortran)
virtual QCString TranslatorChinesetraditional::trModulesMembers()
This is put above each page as a link to all members of modules. (Fortran)
virtual QCString TranslatorChinesetraditional::trModulesMemberDescription(bool extractAll)
This is an introduction to the page with all modules members (Fortran)
virtual QCString TranslatorChinesetraditional::trModulesIndex()
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
virtual QCString TranslatorChinesetraditional::trModule(bool, bool)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorChinesetraditional::trGeneratedFromFilesFortran(ClassDef::CompoundType compType, bool)
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
virtual QCString TranslatorChinesetraditional::trType(bool, bool)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorChinesetraditional::trSubprogram(bool, bool)
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
virtual QCString TranslatorChinesetraditional::trTypeConstraints()
C# Type Constraint list
virtual QCString TranslatorChinesetraditional::trDirRelation(const char *name)
directory relation for name
virtual QCString TranslatorChinesetraditional::trLoading()
Loading message shown when loading search results
virtual QCString TranslatorChinesetraditional::trGlobalNamespace()
Label used for search results in the global namespace
virtual QCString TranslatorChinesetraditional::trSearching()
Message shown while searching
virtual QCString TranslatorChinesetraditional::trNoMatches()
Text shown when no search results are found
virtual QCString TranslatorChinesetraditional::trDirDependency(const char *name)
introduction text for the directory dependency graph
virtual QCString TranslatorChinesetraditional::trFileIn(const char *name)
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
virtual QCString TranslatorChinesetraditional::trIncludesFileIn(const char *name)
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
virtual QCString TranslatorChinesetraditional::trDateTime(int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
Compiles a date string.
year Year in 4 digits month Month of the year: 1=January day Day of the Month: 1..31 dayOfWeek Day of the week: 1=Monday..7=Sunday hour Hour of the day: 0..23 minutes Minutes in the hour: 0..59 seconds Seconds within the minute: 0..59 includeTime Include time in the result string?
virtual QCString TranslatorChinesetraditional::trCiteReferences()
Header for the page with bibliographic citations
virtual QCString TranslatorChinesetraditional::trCopyright()
Text for copyright paragraph
virtual QCString TranslatorChinesetraditional::trDirDepGraph(const char *name)
Header for the graph showing the directory dependencies