ArgumentList
bool ArgumentList::constSpecifier
Does the member modify the state of the class? default: FALSE.
Referenced by deepCopy, unmarshal.
bool ArgumentList::volatileSpecifier
Is the member volatile? default: FALSE.
Referenced by deepCopy, unmarshal.
bool ArgumentList::pureSpecifier
Is this a pure virtual member? default: FALSE
Referenced by deepCopy, unmarshal.
QCString ArgumentList::trailingReturnType
C++11 style Trailing return type?
Referenced by deepCopy, unmarshal.
ArgumentList::ArgumentList()
Creates an empty argument list
Referenced by deepCopy, unmarshal.
ArgumentList::~ArgumentList()
Destroys the argument list
ArgumentList * ArgumentList::deepCopy() const
Makes a deep copy of this object
References ArgumentList, constSpecifier, pureSpecifier, trailingReturnType, volatileSpecifier.
Referenced by copyArgumentLists.
bool ArgumentList::hasDocumentation() const
Does any argument of this list have documentation?the argument list is documented if one of its arguments is documented
References Argument::hasDocumentation.
Referenced by MemberDef::writeDocumentation.
ArgumentList * ArgumentList::unmarshal(StorageIntf *s)
C++11 defaulted method
References ArgumentList, Argument::array, Argument::attrib, Argument::canType, constSpecifier, Argument::defval, Argument::docs, Argument::name, pureSpecifier, trailingReturnType, Argument::type, volatileSpecifier.
void ArgumentList::marshal(StorageIntf *s, ArgumentList *argList)