ClassDef
CompoundType
bool ClassDef::visited
ClassDefImpl* ClassDef::m_impl
ClassDef::ClassDef(const char *fileName, int startLine, int startColumn, const char *name, CompoundType ct, const char *ref=0, const char *fName=0, bool isSymbol=TRUE, bool isJavaEnum=FALSE)
Creates a new compound definition.
fileName full path and file name in which this compound was found. startLine line number where the definition of this compound starts. startColumn column number where the definition of this compound starts. name the name of this compound (including scope) symId unique Id for this symbol ct the kind of Compound ref the tag file from which this compound is extracted or 0 if the compound doesn't come from a tag file fName the file name as found in the tag file. This overwrites the file that doxygen normally generates based on the compound type & name. isSymbol If TRUE this class name is added as a publicly visible (and referencable) symbol. isJavaEnum If TRUE this class is actually a Java enum. I didn't add this to CompoundType to avoid having to adapt all translators.
References compoundTypeString, Definition::name, Definition::setReference.
ClassDef::~ClassDef()
Destroys a compound definition.
DefType ClassDef::definitionType() const
Used for RTTI, this is a class.
QCString ClassDef::getOutputFileBase() const
Returns the unique base name (without extension) of the class's file on disk.
References getFileDef, isLinkableInProject, FileDef::getOutputFileBase, Definition::isLinkableInProject, Definition::getOutputFileBase, isReference.
Referenced by writeInlineDocumentation, MemberList::writeDeclarations, VhdlDocGen::writeVHDLDeclaration.
QCString ClassDef::getInstanceOutputFileBase() const
QCString ClassDef::getFileBase() const
QCString ClassDef::getSourceFileBase() const
Returns the base name for the source code file.
QCString ClassDef::getReference() const
If this class originated from a tagfile, this will return the tag file reference.
References Definition::getReference.
Referenced by MemberList::writeDeclarations, VhdlDocGen::writeVHDLDeclaration.
bool ClassDef::isReference() const
Returns TRUE if this class is imported via a tag file.
References Definition::isReference.
Referenced by hasNonReferenceSuperClass, isLinkableInProject, isLinkable, isVisibleInHierarchy, getOutputFileBase, anchor.
bool ClassDef::isLocal() const
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES.
Referenced by mergeCategory.
ClassSDict * ClassDef::getClassSDict()
returns the classes nested into this class
bool ClassDef::hasDocumentation() const
returns TRUE if this class has documentation
References Definition::hasDocumentation.
Referenced by isLinkableInProject, isVisibleInHierarchy.
QCString ClassDef::displayName(bool includeScope=TRUE) const
Returns the name as it is appears in the documentation.
References Definition::getLanguage, className.
Referenced by MemberDef::writeDocumentation, MemberList::writeDeclarations, VhdlDocGen::getClassTitle.
ClassDef::CompoundType ClassDef::compoundType() const
Returns the type of compound this is, i.e.
class/struct/union/..
Referenced by mergeMembers.
QCString ClassDef::compoundTypeString() const
Returns the type of compound as a string.
References Definition::getLanguage.
Referenced by ClassDef, writeInlineDocumentation, writeDeclaration.
BaseClassList * ClassDef::baseClasses() const
Returns the list of base classes from which this class directly inherits.
Referenced by isBaseClass, mergeMembers, mergeCategory.
BaseClassList * ClassDef::subClasses() const
Returns the list of sub classes that directly derive from this class.
Referenced by isSubClass.
MemberNameInfoSDict * ClassDef::memberNameInfoSDict() const
Returns a dictionary of all members.
This includes any inherited members. Members are sorted alphabetically.
Referenced by mergeCategory, mergeMembers.
Protection ClassDef::protection() const
Return the protection level (Public,Protected,Private) in which this compound was found.
Referenced by VhdlDocGen::getClassTitle, VhdlDocGen::writeInlineClassLink, VhdlDocGen::writeVHDLDeclaration.
bool ClassDef::isLinkableInProject() const
returns TRUE iff a link is possible to this item within this project.
a link to this class is possible within this project
References hasDocumentation, Definition::isArtificial, Definition::isHidden, isReference, Definition::name.
Referenced by getOutputFileBase, hasNonReferenceSuperClass, isLinkable.
bool ClassDef::isLinkable() const
return TRUE iff a link to this class is possible (either within this project, or as a cross-reference to another project).
References isLinkableInProject, isReference.
Referenced by writeDeclaration, getMemberByName, getDefs.
bool ClassDef::isVisibleInHierarchy()
the class is visible in a class diagram, or class hierarchy
References hasDocumentation, hasNonReferenceSuperClass, isReference, Definition::name.
ArgumentList * ClassDef::templateArguments() const
Returns the template arguments of this class Will return 0 if not applicable.
Referenced by getTemplateParameterLists, newResolveTypedef.
NamespaceDef * ClassDef::getNamespaceDef() const
Returns the namespace this compound is in, or 0 if it has a global scope.
FileDef * ClassDef::getFileDef() const
Returns the file in which this compound's definition can be found.
Should not return 0 (but it might be a good idea to check anyway).
Referenced by getDefs, getOutputFileBase.
MemberDef * ClassDef::getMemberByName(const QCString &) const
Returns the Java package this class is in or 0 if not applicable.
References isLinkable.
bool ClassDef::isBaseClass(ClassDef *bcd, bool followInstances, int level=0)
Returns TRUE iff bcd is a direct or indirect base class of this class.
This function will recusively traverse all branches of the inheritance tree.
References baseClasses, isBaseClass, Definition::name, templateMaster.
Referenced by isAccessibleMember, isBaseClass, mergeMembers.
bool ClassDef::isSubClass(ClassDef *bcd, int level=0)
Returns TRUE iff bcd is a direct or indirect sub class of this class.
References Definition::name, subClasses, isSubClass.
Referenced by isSubClass.
bool ClassDef::isAccessibleMember(MemberDef *md)
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
References isBaseClass.
QDict< ClassDef > * ClassDef::getTemplateInstances() const
Returns a sorted dictionary with all template instances found for this template class.
Returns 0 if not a template or no instances.
Referenced by hasNonReferenceSuperClass.
ClassDef * ClassDef::templateMaster() const
Returns the template master of which this class is an instance.
Returns 0 if not applicable.
Referenced by isBaseClass.
bool ClassDef::isTemplate() const
Returns TRUE if this class is a template.
Referenced by newResolveTypedef.
IncludeInfo * ClassDef::includeInfo() const
UsesClassDict * ClassDef::usedImplementationClasses() const
UsesClassDict * ClassDef::usedByImplementationClasses() const
UsesClassDict * ClassDef::usedInterfaceClasses() const
bool ClassDef::isTemplateArgument() const
Definition * ClassDef::findInnerCompound(const char *name)
Returns the definition of a nested compound if available, or 0 otherwise.
name The name of the nested compound
void ClassDef::getTemplateParameterLists(QList< ArgumentList > &lists) const
Returns the template parameter lists that form the template declaration of this class.
Example: template<class T> class TC {}; will return a list with one ArgumentList containing one argument with type="class" and name="T".
References DefinitionIntf::definitionType, getTemplateParameterLists, templateArguments.
Referenced by getTemplateParameterLists, MemberDef::writeDocumentation.
QCString ClassDef::qualifiedNameWithTemplateParameters(QList< ArgumentList > *actualParams=0) const
bool ClassDef::isAbstract() const
Returns TRUE if there is at least one pure virtual member in this class.
bool ClassDef::isObjectiveC() const
Returns TRUE if this class is implemented in Objective-C.
References Definition::getLanguage.
Referenced by MemberDef::writeDocumentation.
bool ClassDef::isCSharp() const
Returns TRUE if this class is implemented in C#.
References Definition::getLanguage.
bool ClassDef::isFinal() const
Returns TRUE if this class is marked as final.
bool ClassDef::isSealed() const
Returns TRUE if this class is marked as sealed.
bool ClassDef::isPublished() const
Returns TRUE if this class is marked as published.
bool ClassDef::isExtension() const
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
References Definition::name.
Referenced by mergeCategory.
ClassDef * ClassDef::categoryOf() const
Returns the class of which this is a category (Objective-C only)
QCString ClassDef::className() const
Returns the name of the class including outer classes, but not including namespaces.
References Definition::localName.
Referenced by displayName, VhdlDocGen::writeInlineClassLink.
MemberList * ClassDef::getMemberList(MemberListType lt)
Returns the members in the list identified by lt.
Referenced by VhdlDocGen::findMemberDef, VhdlDocGen::findAllPackages, VhdlDocGen::findFunction.
const QList< MemberList > & ClassDef::getMemberLists() const
Returns the list containing the list of members sorted per type.
MemberGroupSDict * ClassDef::getMemberGroupSDict() const
Returns the member groups defined for this class.
QDict< int > * ClassDef::getTemplateBaseClassNames() const
ClassDef * ClassDef::getVariableInstance(const char *templSpec)
bool ClassDef::isUsedOnly() const
QCString ClassDef::anchor() const
Returns the anchor within a page where this item can be found
References isReference.
Referenced by MemberList::writeDeclarations, writeInlineDocumentation.
bool ClassDef::isEmbeddedInOuterScope() const
bool ClassDef::isSimple() const
const ClassList * ClassDef::taggedInnerClasses() const
ClassDef * ClassDef::tagLessReference() const
MemberDef * ClassDef::isSmartPointer() const
bool ClassDef::isJavaEnum() const
bool ClassDef::isGeneric() const
void ClassDef::insertBaseClass(ClassDef *, const char *name, Protection p, Specifier s, const char *t=0)
void ClassDef::insertSubClass(ClassDef *, Protection p, Specifier s, const char *t=0)
void ClassDef::setIncludeFile(FileDef *fd, const char *incName, bool local, bool force)
void ClassDef::insertMember(MemberDef *)
void ClassDef::insertUsedFile(const char *)
bool ClassDef::addExample(const char *anchor, const char *name, const char *file)
void ClassDef::mergeCategory(ClassDef *category)
Merges the members of a Objective-C category into this class.
References SDict< T >::append, baseClasses, BaseClassDef::classDef, SDict< T >::find, isExtension, isLocal, memberNameInfoSDict, Definition::name.
void ClassDef::setNamespace(NamespaceDef *nd)
void ClassDef::setFileDef(FileDef *fd)
void ClassDef::setSubGrouping(bool enabled)
void ClassDef::setProtection(Protection p)
void ClassDef::setGroupDefForAllMembers(GroupDef *g, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs)
void ClassDef::addInnerCompound(Definition *d)
ClassDef * ClassDef::insertTemplateInstance(const QCString &fileName, int startLine, int startColumn, const QCString &templSpec, bool &freshInstance)
void ClassDef::addUsedClass(ClassDef *cd, const char *accessName, Protection prot)
void ClassDef::addUsedByClass(ClassDef *cd, const char *accessName, Protection prot)
void ClassDef::setIsStatic(bool b)
void ClassDef::setCompoundType(CompoundType t)
void ClassDef::setClassName(const char *name)
void ClassDef::setClassSpecifier(uint64 spec)
void ClassDef::setTemplateArguments(ArgumentList *al)
void ClassDef::setTemplateBaseClassNames(QDict< int > *templateNames)
void ClassDef::setTemplateMaster(ClassDef *tm)
void ClassDef::setTypeConstraints(ArgumentList *al)
void ClassDef::addMembersToTemplateInstance(ClassDef *cd, const char *templSpec)
void ClassDef::makeTemplateArgument(bool b=TRUE)
void ClassDef::setCategoryOf(ClassDef *cd)
void ClassDef::setUsedOnly(bool b)
void ClassDef::addTaggedInnerClass(ClassDef *cd)
void ClassDef::setTagLessReference(ClassDef *cd)
void ClassDef::findSectionsInDocumentation()
void ClassDef::addMembersToMemberGroup()
void ClassDef::addListReferences()
void ClassDef::computeAnchors()
void ClassDef::mergeMembers()
recusively merges the `all members' lists of a class base with that of this class. Must only be called for classes without subclasses!
References SDict< T >::append, baseClasses, BaseClassDef::classDef, compoundType, SDict< T >::find, Definition::getLanguage, isBaseClass, memberNameInfoSDict, mergeMembers, Definition::name, BaseClassDef::prot, BaseClassDef::virt.
Referenced by mergeMembers.
void ClassDef::sortMemberLists()
void ClassDef::distributeMemberGroupDocumentation()
void ClassDef::writeDocumentation(OutputList &ol)
void ClassDef::writeDocumentationForInnerClasses(OutputList &ol)
void ClassDef::writeMemberPages(OutputList &ol)
void ClassDef::writeMemberList(OutputList &ol)
void ClassDef::writeDeclaration(OutputList &ol, MemberDef *md, bool inGroup, ClassDef *inheritedFrom, const char *inheritId)
called from MemberDef::writeDeclaration() to (recusively) write the definition of an anonymous struct, union or class.
References MemberDef::anchor, compoundTypeString, OutputList::docify, OutputList::endBold, LayoutDocManager::instance, isLinkable, Definition::name, OutputList::startBold, OutputList::writeObjectLink.
Referenced by MemberDef::writeDeclaration.
void ClassDef::writeQuickMemberLinks(OutputList &ol, MemberDef *md) const
void ClassDef::writeSummaryLinks(OutputList &ol)
void ClassDef::reclassifyMember(MemberDef *md, MemberType t)
void ClassDef::writeInlineDocumentation(OutputList &ol)
Write class documentation inside another container (i.e.
a group)
References anchor, compoundTypeString, OutputList::disable, OutputList::disableAllBut, Definition::getLanguage, getOutputFileBase, LayoutDocManager::instance, Definition::name, OutputList::popGeneratorState, OutputList::pushGeneratorState, OutputList::writeString.
void ClassDef::writeDeclarationLink(OutputList &ol, bool &found, const char *header, bool localNames)
void ClassDef::removeMemberFromLists(MemberDef *md)
void ClassDef::addGroupedInheritedMembers(OutputList &ol, MemberListType lt, ClassDef *inheritedFrom, const QCString &inheritId)
int ClassDef::countMembersIncludingGrouped(MemberListType lt, ClassDef *inheritedFrom, bool additional)
void ClassDef::addUsedInterfaceClasses(MemberDef *md, const char *typeStr)
bool ClassDef::hasExamples()
bool ClassDef::hasNonReferenceSuperClass()
Returns TRUE iff this class or a class inheriting from this class is not defined in an external tag file.
References getTemplateInstances, hasNonReferenceSuperClass, Definition::isHidden, isLinkableInProject, isReference.
Referenced by hasNonReferenceSuperClass, isVisibleInHierarchy.
void ClassDef::showUsedFiles(OutputList &ol)
void ClassDef::writeTagFileMarker()
void ClassDef::writeDocumentationContents(OutputList &ol, const QCString &pageTitle)
void ClassDef::internalInsertMember(MemberDef *md, Protection prot, bool addToAllList)
QCString ClassDef::getMemberListFileName() const
void ClassDef::addMemberToList(MemberListType lt, MemberDef *md, bool isBrief)
MemberList * ClassDef::createMemberList(MemberListType lt)
void ClassDef::writeInheritedMemberDeclarations(OutputList &ol, MemberListType lt, const QCString &title, ClassDef *inheritedFrom, bool invert, QPtrDict< void > *visitedClasses)
void ClassDef::writeMemberDeclarations(OutputList &ol, MemberListType lt, const QCString &title, const char *subTitle=0, bool showInline=FALSE, ClassDef *inheritedFrom=0, int lt2=-1, bool invert=FALSE, QPtrDict< void > *visitedClasses=0)
void ClassDef::writeMemberDocumentation(OutputList &ol, MemberListType lt, const QCString &title, bool showInline=FALSE)
void ClassDef::writeSimpleMemberDocumentation(OutputList &ol, MemberListType lt)
void ClassDef::writePlainMemberDeclaration(OutputList &ol, MemberListType lt, bool inGroup, ClassDef *inheritedFrom, const char *inheritId)
void ClassDef::writeBriefDescription(OutputList &ol, bool exampleFlag)
void ClassDef::writeDetailedDescription(OutputList &ol, const QCString &pageType, bool exampleFlag, const QCString &title, const QCString &anchor=QCString())
void ClassDef::writeIncludeFiles(OutputList &ol)
void ClassDef::writeInheritanceGraph(OutputList &ol)
void ClassDef::writeCollaborationGraph(OutputList &ol)
void ClassDef::writeMemberGroups(OutputList &ol, bool showInline=FALSE)
void ClassDef::writeNestedClasses(OutputList &ol, const QCString &title)
void ClassDef::writeInlineClasses(OutputList &ol)
void ClassDef::startMemberDeclarations(OutputList &ol)
void ClassDef::endMemberDeclarations(OutputList &ol)
void ClassDef::startMemberDocumentation(OutputList &ol)
void ClassDef::endMemberDocumentation(OutputList &ol)
void ClassDef::writeAuthorSection(OutputList &ol)
void ClassDef::writeMoreLink(OutputList &ol, const QCString &anchor)
void ClassDef::writeDetailedDocumentationBody(OutputList &ol)
int ClassDef::countInheritedDecMembersRec(MemberListType lt, ClassDef *inheritedFrom)
int ClassDef::countInheritedDecMembers(MemberListType lt)
int ClassDef::countAdditionalInheritedMembers()
void ClassDef::writeAdditionalInheritedMembers(OutputList &ol)
void ClassDef::addClassAttributes(OutputList &ol)