Definition
DefinitionImpl* Definition::m_impl
QCString Definition::m_name
bool Definition::m_isSymbol
QCString Definition::m_symbolName
int Definition::m_defLine
int Definition::m_defColumn
Definition::Definition(const char *defFileName, int defLine, int defColumn, const char *name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
Create a new definition
References name.
Definition::~Definition()
Destroys the definition
const QCString& Definition::name() const
Returns the name of the definition
Referenced by ClassDef::ClassDef, MemberSDict::compareItems, MemberList::countDecMembers, Definition, GroupDef::displayName, PageDef::displayName, NamespaceDef::displayName, MemberDef::displayName, extractNamespaceName, VhdlDocGen::findAllPackages, VhdlDocGen::findFunction, VhdlDocGen::findMemberDef, MemberDef::getClassDefOfAnonymousType, getDefs, MemberDef::getOutputFileBase, FileDef::insertClass, FileDef::insertMember, FileDef::insertNamespace, ClassDef::isBaseClass, ClassDef::isExtension, NamespaceDef::isLinkableInProject, ClassDef::isLinkableInProject, ClassDef::isSubClass, ClassDef::isVisibleInHierarchy, ClassDef::mergeCategory, ClassDef::mergeMembers, FileDef::name, MemberDef::qualifiedName, setName, MemberDef::writeDeclaration, ClassDef::writeDeclaration, MemberDef::writeDocumentation, ClassDef::writeInlineDocumentation, VhdlDocGen::writeVHDLDeclaration.
virtual QCString Definition::displayName(bool includeScope=TRUE) const =0
Returns the name of the definition as it appears in the output
Referenced by briefDescription, MemberDef::writeDeclaration.
QCString Definition::localName() const
Returns the local name without any scope qualifiers.
Referenced by ClassDef::className, navigationPathAsString, FileDef::writeDocumentation, VhdlDocGen::writeVHDLDeclaration.
QCString Definition::qualifiedName() const
Returns the fully qualified name of this definition
References getLanguage.
Referenced by newResolveTypedef, MemberDef::qualifiedName.
QCString Definition::symbolName() const
Returns the name of this definition as it appears in the symbol map.
virtual QCString Definition::getOutputFileBase() const =0
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Referenced by ClassDef::getOutputFileBase, navigationPathAsString, MemberDef::writeDocumentation, VhdlDocGen::writeVHDLDeclaration.
virtual QCString Definition::anchor() const =0
Returns the anchor within a page where this item can be found
Referenced by navigationPathAsString.
virtual QCString Definition::getSourceFileBase() const
Returns the name of the source listing of this file.
QCString Definition::documentation() const
Returns the detailed description of this definition
Referenced by MemberDef::isBriefSectionVisible, MemberDef::writeDocumentation.
int Definition::docLine() const
Returns the line number at which the detailed documentation was found.
Referenced by MemberDef::writeDocumentation.
QCString Definition::docFile() const
Returns the file in which the detailed documentation block was found. This can differ from getDefFileName().
Referenced by MemberDef::writeDocumentation.
QCString Definition::briefDescription(bool abbreviate=FALSE) const
Returns the brief description of this definition. This can include commands.
References displayName.
Referenced by MemberDef::writeDeclaration, MemberDef::writeDocumentation, VhdlDocGen::writeVHDLDeclaration.
QCString Definition::briefDescriptionAsTooltip() const
Returns a plain text version of the brief description suitable for use as a tool tip.
References DefinitionIntf::definitionType.
int Definition::briefLine() const
Returns the line number at which the brief description was found.
Referenced by MemberDef::writeDeclaration, MemberDef::writeDocumentation, VhdlDocGen::writeVHDLDeclaration.
QCString Definition::inbodyDocumentation() const
Returns the documentation found inside the body of a member
Referenced by MemberDef::writeDocumentation.
QCString Definition::inbodyFile() const
Returns the file in which the in body documentation was found
Referenced by MemberDef::writeDocumentation.
int Definition::inbodyLine() const
Returns the line at which the first in body documentation part was found
Referenced by MemberDef::writeDocumentation.
QCString Definition::briefFile() const
Returns the file in which the brief description was found. This can differ from getDefFileName().
Referenced by MemberDef::writeDeclaration, MemberDef::writeDocumentation, VhdlDocGen::writeVHDLDeclaration.
QCString Definition::getDefFileName() const
returns the file in which this definition was found
Referenced by MemberDef::getOutputFileBase, newResolveTypedef.
QCString Definition::getDefFileExtension() const
returns the extension of the file in which this definition was found
Referenced by MemberDef::writeDocumentation, FileDef::writeSource.
int Definition::getDefLine() const
returns the line number at which the definition was found
Referenced by MemberSDict::compareItems, MemberDef::getOutputFileBase.
int Definition::getDefColumn() const
returns the column number at which the definition was found
bool Definition::hasDocumentation() const
Returns TRUE iff the definition is documented (which could be generated documentation) hasUserDocumentation()
Referenced by ClassDef::hasDocumentation, MemberDef::hasDocumentation, NamespaceDef::isLinkableInProject, FileDef::isLinkableInProject.
bool Definition::hasUserDocumentation() const
Returns TRUE iff the definition is documented by the user.
Referenced by GroupDef::isLinkable.
virtual bool Definition::isLinkableInProject() const =0
Returns TRUE iff it is possible to link to this item within this project.
Referenced by ClassDef::getOutputFileBase, isVisibleInProject.
virtual bool Definition::isLinkable() const =0
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Referenced by isVisible, navigationPathAsString.
bool Definition::isVisibleInProject() const
Returns TRUE iff the name is part of this project and may appear in the output
References isLinkableInProject.
bool Definition::isVisible() const
Returns TRUE iff the name may appear in the output
References isLinkable.
bool Definition::isHidden() const
Returns TRUE iff this item is supposed to be hidden from the output.
Referenced by ClassDef::hasNonReferenceSuperClass, FileDef::insertClass, FileDef::insertMember, FileDef::insertNamespace, MemberDef::isBriefSectionVisible, NamespaceDef::isLinkableInProject, ClassDef::isLinkableInProject.
bool Definition::isArtificial() const
returns TRUE if this entity was artificially introduced, for instance because it is used to show a template instantiation relation.
Referenced by NamespaceDef::isLinkableInProject, ClassDef::isLinkableInProject.
QCString Definition::getReference() const
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Referenced by MemberDef::getReference, ClassDef::getReference.
bool Definition::isReference() const
Returns TRUE if this definition is imported via a tag file.
Referenced by NamespaceDef::getOutputFileBase, GroupDef::getOutputFileBase, PageDef::isLinkable, DirDef::isLinkable, NamespaceDef::isLinkable, FileDef::isLinkable, MemberDef::isLinkable, PageDef::isLinkableInProject, DirDef::isLinkableInProject, GroupDef::isLinkableInProject, NamespaceDef::isLinkableInProject, FileDef::isLinkableInProject, ClassDef::isReference, MemberDef::writeDeclaration.
int Definition::getStartBodyLine() const
Returns the first line of the body of this item (applicable to classes and functions).
int Definition::getEndBodyLine() const
Returns the last line of the body of this item (applicable to classes and functions).
FileDef * Definition::getBodyDef()
Returns the file in which the body of this item is located or 0 if no body is available.
Referenced by MemberDef::writeDeclaration, MemberDef::writeDocumentation.
SrcLangExt Definition::getLanguage() const
Returns the programming language this definition was written in.
Referenced by ClassDef::compoundTypeString, NamespaceDef::displayName, ClassDef::displayName, ClassDef::isCSharp, NamespaceDef::isLinkableInProject, ClassDef::isObjectiveC, ClassDef::mergeMembers, qualifiedName, MemberDef::writeDeclaration, FileDef::writeDocumentation, MemberDef::writeDocumentation, ClassDef::writeInlineDocumentation, FileDef::writeSource.
GroupList * Definition::partOfGroups() const
QList< ListItemInfo > * Definition::xrefListItems() const
Definition * Definition::findInnerCompound(const char *name)
Definition * Definition::getOuterScope() const
MemberSDict * Definition::getReferencesMembers() const
MemberSDict * Definition::getReferencedByMembers() const
bool Definition::hasSections() const
QCString Definition::id() const
void Definition::setName(const char *name)
Sets a new name for the definition
References name.
Referenced by VhdlDocGen::writeVHDLDeclaration.
void Definition::setId(const char *name)
Sets a unique id for the symbol. Used for libclang integration.
void Definition::setDocumentation(const char *d, const char *docFile, int docLine, bool stripWhiteSpace=TRUE)
Sets the documentation of this definition to d.
Referenced by MemberDef::setDocumentation.
void Definition::setBriefDescription(const char *b, const char *briefFile, int briefLine)
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
Referenced by MemberDef::setBriefDescription.
void Definition::setInbodyDocumentation(const char *d, const char *docFile, int docLine)
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
Referenced by MemberDef::setInbodyDocumentation.
void Definition::setReference(const char *r)
Sets the tag file id via which this definition was imported.
Referenced by ClassDef::ClassDef, FileDef::FileDef.
void Definition::addSectionsToDefinition(QList< SectionInfo > *anchorList)
Add the list of anchors that mark the sections that are found in the documentation.
References SDict< T >::append, SDict< T >::find.
void Definition::setBodySegment(int bls, int ble)
void Definition::setBodyDef(FileDef *fd)
void Definition::addSourceReferencedBy(MemberDef *d)
void Definition::addSourceReferences(MemberDef *d)
void Definition::setRefItems(const QList< ListItemInfo > *sli)
void Definition::mergeRefItems(Definition *d)
void Definition::addInnerCompound(Definition *d)
void Definition::setOuterScope(Definition *d)
void Definition::setHidden(bool b)
void Definition::setArtificial(bool b)
void Definition::setLanguage(SrcLangExt lang)
QCString Definition::convertNameToFile(const char *name, bool allowDots=FALSE) const
void Definition::writeSourceDef(OutputList &ol, const char *scopeName)
Write a reference to the source code defining this definition
References OutputList::disable, OutputList::disableAllBut, OutputList::docify, OutputList::enableAll, OutputList::endParagraph, OutputList::popGeneratorState, OutputList::pushGeneratorState, OutputList::startParagraph, OutputList::writeObjectLink.
Referenced by MemberDef::writeDocumentation.
void Definition::writeInlineCode(OutputList &ol, const char *scopeName)
Write code of this definition into the documentation
References DefinitionIntf::definitionType, OutputList::endCodeFragment, ParserManager::getParser, ParserInterface::parseCode, OutputList::popGeneratorState, OutputList::pushGeneratorState, ParserInterface::resetCodeParserState, OutputList::startCodeFragment.
Referenced by MemberDef::writeDocumentation.
void Definition::writeSourceRefs(OutputList &ol, const char *scopeName)
void Definition::writeSourceReffedBy(OutputList &ol, const char *scopeName)
void Definition::makePartOfGroup(GroupDef *gd)
void Definition::writeNavigationPath(OutputList &ol) const
QCString Definition::navigationPathAsString() const
Returns the string used in the footer for $navpath when GENERATE_TREEVIEW is enabled
References anchor, DefinitionIntf::definitionType, getOutputFileBase, isLinkable, localName, navigationPathAsString.
Referenced by navigationPathAsString.
virtual void Definition::writeQuickMemberLinks(OutputList &, MemberDef *) const
virtual void Definition::writeSummaryLinks(OutputList &)
QCString Definition::pathFragment() const
void Definition::writeDocAnchorsToTagFile()
Writes the documentation anchors of the definition to the Doxygen::tagFile stream.
References DefinitionIntf::definitionType.
Referenced by FileDef::writeDocumentation, VhdlDocGen::writeVHDLDeclaration.
void Definition::setLocalName(const QCString name)
void Definition::addSectionsToIndex()
void Definition::writeToc(OutputList &ol)
Definition::Definition(const Definition &d)
void Definition::addToMap(const char *name, Definition *d)
void Definition::removeFromMap(Definition *d)
void Definition::_setSymbolName(const QCString &name)
int Definition::_getXRefListId(const char *listName) const
void Definition::_writeSourceRefList(OutputList &ol, const char *scopeName, const QCString &text, MemberSDict *members, bool)
Write a reference to the source code fragments in which this definition is used.
void Definition::_setBriefDescription(const char *b, const char *briefFile, int briefLine)
void Definition::_setDocumentation(const char *d, const char *docFile, int docLine, bool stripWhiteSpace, bool atTop)
void Definition::_setInbodyDocumentation(const char *d, const char *docFile, int docLine)
bool Definition::_docsAlreadyAdded(const QCString &doc)