MemberDef
bool MemberDef::visited
int MemberDef::s_indentLevel
MemberDefImpl* MemberDef::m_impl
uchar MemberDef::m_isLinkableCached
uchar MemberDef::m_isConstructorCached
uchar MemberDef::m_isDestructorCached
MemberDef::MemberDef(const char *defFileName, int defLine, int defColumn, const char *type, const char *name, const char *args, const char *excp, Protection prot, Specifier virt, bool stat, Relationship related, MemberType t, const ArgumentList *tal, const ArgumentList *al)
Creates a new member definition. df File containing the definition of this member. dl Line at which the member definition was found. dc Column at which the member definition was found. t A string representing the type of the member. na A string representing the name of the member. a A string representing the arguments of the member. e A string representing the throw clause of the members. p The protection context of the member, possible values are: Public, Protected, Private. v The degree of `virtualness' of the member, possible values are: Normal, Virtual, Pure. s A boolean that is true iff the member is static. r The relationship between the class and the member. mt The kind of member. See #MemberType for a list of all types. tal The template arguments of this member. al The arguments of this member. This is a structured form of the string past as argument a.
MemberDef::~MemberDef()
Destroys the member definition.
DefType MemberDef::definitionType() const
Use this for dynamic inspection of the type of the derived class
Referenced by writeDocumentation.
MemberDef * MemberDef::deepCopy() const
void MemberDef::moveTo(Definition *)
QCString MemberDef::getOutputFileBase() const
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
References anchor, Definition::getDefFileName, Definition::getDefLine, Definition::name.
Referenced by writeDeclaration, writeDocumentation, VhdlDocGen::writeVHDLDeclaration.
QCString MemberDef::getReference() const
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
References Definition::getReference.
Referenced by anchor, VhdlDocGen::writeVHDLDeclaration.
QCString MemberDef::anchor() const
Returns the anchor within a page where this item can be found
References getReference.
Referenced by getOutputFileBase, writeDeclaration, ClassDef::writeDeclaration, writeDocumentation, VhdlDocGen::writeVHDLDeclaration.
const char * MemberDef::declaration() const
const char * MemberDef::definition() const
const char * MemberDef::typeString() const
const char * MemberDef::argsString() const
const char * MemberDef::excpString() const
const char * MemberDef::bitfieldString() const
const char * MemberDef::extraTypeChars() const
const QCString & MemberDef::initializer() const
int MemberDef::initializerLines() const
uint64 MemberDef::getMemberSpecifiers() const
MemberList * MemberDef::getSectionList(Definition *d) const
ClassDef * MemberDef::getClassDef() const
FileDef * MemberDef::getFileDef() const
NamespaceDef * MemberDef::getNamespaceDef() const
const char * MemberDef::getReadAccessor() const
const char * MemberDef::getWriteAccessor() const
GroupDef * MemberDef::getGroupDef() const
Grouping::GroupPri_t MemberDef::getGroupPri() const
const char * MemberDef::getGroupFileName() const
int MemberDef::getGroupStartLine() const
bool MemberDef::getGroupHasDocs() const
QCString MemberDef::qualifiedName() const
Returns the fully qualified name of this definition
References Definition::name, Definition::qualifiedName.
Referenced by newResolveTypedef, writeDocumentation, VhdlDocGen::writeVHDLDeclaration.
QCString MemberDef::objCMethodName(bool localLink, bool showStatic) const
Protection MemberDef::protection() const
Specifier MemberDef::virtualness(int count=0) const
MemberType MemberDef::memberType() const
QCString MemberDef::memberTypeName() const
bool MemberDef::isSignal() const
bool MemberDef::isSlot() const
bool MemberDef::isVariable() const
bool MemberDef::isEnumerate() const
bool MemberDef::isEnumValue() const
bool MemberDef::isTypedef() const
bool MemberDef::isFunction() const
bool MemberDef::isFunctionPtr() const
bool MemberDef::isDefine() const
bool MemberDef::isFriend() const
bool MemberDef::isDCOP() const
bool MemberDef::isProperty() const
bool MemberDef::isEvent() const
bool MemberDef::isRelated() const
bool MemberDef::isForeign() const
bool MemberDef::isStatic() const
bool MemberDef::isInline() const
bool MemberDef::isExplicit() const
bool MemberDef::isMutable() const
bool MemberDef::isGettable() const
bool MemberDef::isSettable() const
bool MemberDef::isReadable() const
bool MemberDef::isWritable() const
bool MemberDef::isAddable() const
bool MemberDef::isRemovable() const
bool MemberDef::isRaisable() const
bool MemberDef::isFinal() const
bool MemberDef::isAbstract() const
bool MemberDef::isOverride() const
bool MemberDef::isInitonly() const
bool MemberDef::isOptional() const
bool MemberDef::isRequired() const
bool MemberDef::isNonAtomic() const
bool MemberDef::isCopy() const
bool MemberDef::isAssign() const
bool MemberDef::isRetain() const
bool MemberDef::isWeak() const
bool MemberDef::isStrong() const
bool MemberDef::isUnretained() const
bool MemberDef::isNew() const
bool MemberDef::isSealed() const
bool MemberDef::isImplementation() const
bool MemberDef::isExternal() const
bool MemberDef::isAlias() const
bool MemberDef::isDefault() const
bool MemberDef::isDelete() const
bool MemberDef::isNoExcept() const
bool MemberDef::isAttribute() const
bool MemberDef::isUNOProperty() const
bool MemberDef::isReadonly() const
bool MemberDef::isBound() const
bool MemberDef::isConstrained() const
bool MemberDef::isTransient() const
bool MemberDef::isMaybeVoid() const
bool MemberDef::isMaybeDefault() const
bool MemberDef::isMaybeAmbiguous() const
bool MemberDef::isPublished() const
bool MemberDef::isTemplateSpecialization() const
bool MemberDef::hasDocumentedParams() const
bool MemberDef::hasDocumentedReturnType() const
bool MemberDef::isObjCMethod() const
bool MemberDef::isObjCProperty() const
bool MemberDef::isConstructor() const
bool MemberDef::isDestructor() const
bool MemberDef::hasOneLineInitializer() const
bool MemberDef::hasMultiLineInitializer() const
bool MemberDef::protectionVisible() const
bool MemberDef::showInCallGraph() const
bool MemberDef::isLinkableInProject() const
Returns TRUE iff it is possible to link to this item within this project.
Referenced by isLinkable.
bool MemberDef::isLinkable() const
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
References isLinkableInProject, Definition::isReference.
Referenced by getDefs.
bool MemberDef::hasDocumentation() const
Returns TRUE iff the definition is documented (which could be generated documentation) hasUserDocumentation()
References Definition::hasDocumentation.
Referenced by MemberList::countDecMembers, isBriefSectionVisible, writeDeclaration, writeDocumentation.
bool MemberDef::isBriefSectionVisible() const
This methods returns TRUE iff the brief section (also known as declaration section) is visible in the documentation.
References Definition::documentation, hasDocumentation, Definition::isHidden.
Referenced by MemberList::countDecMembers.
bool MemberDef::isDetailedSectionVisible(bool inGroup, bool inFile) const
bool MemberDef::isDetailedSectionLinkable() const
bool MemberDef::isFriendClass() const
bool MemberDef::isDocumentedFriendClass() const
MemberDef * MemberDef::reimplements() const
MemberList * MemberDef::reimplementedBy() const
bool MemberDef::isReimplementedBy(ClassDef *cd) const
ClassDef * MemberDef::relatedAlso() const
bool MemberDef::hasDocumentedEnumValues() const
MemberDef * MemberDef::getAnonymousEnumType() const
bool MemberDef::isDocsForDefinition() const
MemberDef * MemberDef::getEnumScope() const
MemberList * MemberDef::enumFieldList() const
void MemberDef::setEnumBaseType(const QCString &type)
QCString MemberDef::enumBaseType() const
bool MemberDef::hasExamples()
ExampleSDict * MemberDef::getExamples() const
bool MemberDef::isPrototype() const
ArgumentList * MemberDef::argumentList() const
ArgumentList * MemberDef::declArgumentList() const
ArgumentList * MemberDef::templateArguments() const
QList< ArgumentList > * MemberDef::definitionTemplateParameterLists() const
int MemberDef::getMemberGroupId() const
MemberGroup * MemberDef::getMemberGroup() const
bool MemberDef::fromAnonymousScope() const
bool MemberDef::anonymousDeclShown() const
bool MemberDef::hasCallGraph() const
bool MemberDef::hasCallerGraph() const
bool MemberDef::visibleMemberGroup(bool hideNoHeader)
MemberDef * MemberDef::templateMaster() const
QCString MemberDef::getScopeString() const
ClassDef * MemberDef::getClassDefOfAnonymousType()
If this member has an anonymous class/struct/union as its type, then this method will return the ClassDef that describes this return type.
References Definition::name.
Referenced by writeDeclaration, VhdlDocGen::writeVHDLDeclaration.
bool MemberDef::isTypedefValCached() const
ClassDef * MemberDef::getCachedTypedefVal() const
QCString MemberDef::getCachedTypedefTemplSpec() const
QCString MemberDef::getCachedResolvedTypedef() const
MemberDef * MemberDef::memberDefinition() const
MemberDef * MemberDef::memberDeclaration() const
MemberDef * MemberDef::inheritsDocsFrom() const
MemberDef * MemberDef::getGroupAlias() const
ClassDef * MemberDef::category() const
MemberDef * MemberDef::categoryRelation() const
QCString MemberDef::displayName(bool=TRUE) const
Returns the name of the definition as it appears in the output
References Definition::name.
void MemberDef::setMemberType(MemberType t)
void MemberDef::setDefinition(const char *d)
void MemberDef::setFileDef(FileDef *fd)
void MemberDef::setAnchor()
void MemberDef::setProtection(Protection p)
void MemberDef::setMemberSpecifiers(uint64 s)
void MemberDef::mergeMemberSpecifiers(uint64 s)
void MemberDef::setInitializer(const char *i)
void MemberDef::setBitfields(const char *s)
void MemberDef::setMaxInitLines(int lines)
void MemberDef::setMemberClass(ClassDef *cd)
void MemberDef::setSectionList(Definition *d, MemberList *sl)
void MemberDef::setGroupDef(GroupDef *gd, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs, MemberDef *member=0)
void MemberDef::setExplicitExternal(bool b)
void MemberDef::setReadAccessor(const char *r)
void MemberDef::setWriteAccessor(const char *w)
void MemberDef::setTemplateSpecialization(bool b)
void MemberDef::makeRelated()
void MemberDef::makeForeign()
void MemberDef::setHasDocumentedParams(bool b)
void MemberDef::setHasDocumentedReturnType(bool b)
void MemberDef::setInheritsDocsFrom(MemberDef *md)
void MemberDef::setTagInfo(TagInfo *i)
void MemberDef::setArgsString(const char *as)
void MemberDef::setReimplements(MemberDef *md)
void MemberDef::insertReimplementedBy(MemberDef *md)
void MemberDef::setRelatedAlso(ClassDef *cd)
void MemberDef::insertEnumField(MemberDef *md)
void MemberDef::setEnumScope(MemberDef *md, bool livesInsideEnum=FALSE)
void MemberDef::setEnumClassScope(ClassDef *cd)
void MemberDef::setDocumentedEnumValues(bool value)
void MemberDef::setAnonymousEnumType(MemberDef *md)
bool MemberDef::addExample(const char *anchor, const char *name, const char *file)
void MemberDef::setPrototype(bool p)
void MemberDef::setArgumentList(ArgumentList *al)
void MemberDef::setDeclArgumentList(ArgumentList *al)
void MemberDef::setDefinitionTemplateParameterLists(QList< ArgumentList > *lists)
void MemberDef::setTypeConstraints(ArgumentList *al)
void MemberDef::setType(const char *t)
void MemberDef::setAccessorType(ClassDef *cd, const char *t)
void MemberDef::setNamespace(NamespaceDef *nd)
void MemberDef::setMemberGroup(MemberGroup *grp)
void MemberDef::setMemberGroupId(int id)
void MemberDef::makeImplementationDetail()
void MemberDef::setFromAnonymousScope(bool b)
void MemberDef::setFromAnonymousMember(MemberDef *m)
void MemberDef::enableCallGraph(bool e)
void MemberDef::enableCallerGraph(bool e)
void MemberDef::setTemplateMaster(MemberDef *mt)
void MemberDef::addListReference(Definition *d)
void MemberDef::setDocsForDefinition(bool b)
void MemberDef::setGroupAlias(MemberDef *md)
void MemberDef::cacheTypedefVal(ClassDef *val, const QCString &templSpec, const QCString &resolvedType)
void MemberDef::invalidateTypedefValCache()
void MemberDef::invalidateCachedArgumentTypes()
void MemberDef::setMemberDefinition(MemberDef *md)
void MemberDef::setMemberDeclaration(MemberDef *md)
void MemberDef::setAnonymousUsed()
void MemberDef::copyArgumentNames(MemberDef *bmd)
void MemberDef::setCategory(ClassDef *)
void MemberDef::setCategoryRelation(MemberDef *)
void MemberDef::setDocumentation(const char *d, const char *docFile, int docLine, bool stripWhiteSpace=TRUE)
Sets the documentation of this definition to d.
References Definition::setDocumentation.
void MemberDef::setBriefDescription(const char *b, const char *briefFile, int briefLine)
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
References Definition::setBriefDescription.
void MemberDef::setInbodyDocumentation(const char *d, const char *inbodyFile, int inbodyLine)
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
References Definition::setInbodyDocumentation.
void MemberDef::setHidden(bool b)
void MemberDef::writeDeclaration(OutputList &ol, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd, bool inGroup, const DefType compoundType, ClassDef *inheritFrom=0, const char *inheritId=0)
References anchor, Definition::briefDescription, Definition::briefFile, Definition::briefLine, OutputList::disable, OutputList::disableAllBut, Definition::displayName, OutputList::docify, OutputList::enable, OutputList::endParagraph, OutputList::endTypewriter, Definition::getBodyDef, getClassDefOfAnonymousType, Definition::getLanguage, getOutputFileBase, hasDocumentation, OutputList::isEnabled, Definition::isReference, Definition::name, OutputList::popGeneratorState, OutputList::pushGeneratorState, OutputList::startParagraph, OutputList::startTypewriter, ClassDef::writeDeclaration, OutputList::writeString.
void MemberDef::writeDocumentation(MemberList *ml, OutputList &ol, const char *scopeName, Definition *container, bool inGroup, bool showEnumValues=FALSE, bool showInline=FALSE)
Writes the "detailed documentation" section of this member to all active output formats.
References anchor, Definition::briefDescription, Definition::briefFile, Definition::briefLine, definitionType, DefinitionIntf::definitionType, OutputList::disable, OutputList::disableAll, OutputList::disableAllBut, NamespaceDef::displayName, FileDef::displayName, ClassDef::displayName, Definition::docFile, OutputList::docify, Definition::docLine, Argument::docs, Definition::documentation, OutputList::enable, OutputList::endBold, OutputList::endCodeFragment, OutputList::endParagraph, Definition::getBodyDef, Definition::getDefFileExtension, Definition::getLanguage, getOutputFileBase, Definition::getOutputFileBase, ParserManager::getParser, ClassDef::getTemplateParameterLists, Argument::hasDocumentation, ArgumentList::hasDocumentation, hasDocumentation, Definition::inbodyDocumentation, Definition::inbodyFile, Definition::inbodyLine, ClassDef::isObjectiveC, Argument::name, Definition::name, ParserInterface::parseCode, OutputList::popGeneratorState, OutputList::pushGeneratorState, qualifiedName, ParserInterface::resetCodeParserState, OutputList::startBold, OutputList::startCodeFragment, OutputList::startParagraph, Definition::writeInlineCode, Definition::writeSourceDef, OutputList::writeString.
void MemberDef::writeMemberDocSimple(OutputList &ol, Definition *container)
void MemberDef::writeEnumDeclaration(OutputList &typeDecl, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd, const DefType compoundType)
void MemberDef::warnIfUndocumented()
MemberDef * MemberDef::createTemplateInstanceMember(ArgumentList *formalArgs, ArgumentList *actualArgs)
void MemberDef::findSectionsInDocumentation()
void MemberDef::flushToDisk() const
void MemberDef::loadFromDisk() const
void MemberDef::lock() const
void MemberDef::unlock() const
void MemberDef::saveToDisk() const
void MemberDef::makeResident() const
void MemberDef::_computeLinkableInProject()
void MemberDef::_computeIsConstructor()
void MemberDef::_computeIsDestructor()
void MemberDef::_getLabels(QStrList &sl, Definition *container) const
void MemberDef::_writeCallGraph(OutputList &ol)
void MemberDef::_writeCallerGraph(OutputList &ol)
void MemberDef::_writeReimplements(OutputList &ol)
void MemberDef::_writeReimplementedBy(OutputList &ol)
void MemberDef::_writeExamples(OutputList &ol)
void MemberDef::_writeTypeConstraints(OutputList &ol)
void MemberDef::_writeEnumValues(OutputList &ol, Definition *container, const QCString &cfname, const QCString &ciname, const QCString &cname)
void MemberDef::_writeCategoryRelation(OutputList &ol)
void MemberDef::_writeTagData(const DefType)
void MemberDef::_addToSearchIndex()
MemberDef::MemberDef(const MemberDef &)
MemberDef& MemberDef::operator=(const MemberDef &)
void MemberDef::writeLink(OutputList &ol, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd, bool onlyText=FALSE)